-- 1. Add notes, follow-up, and advices columns to aka_opd_registration table
ALTER TABLE public.aka_opd_registration ADD COLUMN IF NOT EXISTS notes_for_patient text null;
ALTER TABLE public.aka_opd_registration ADD COLUMN IF NOT EXISTS private_notes text null;
ALTER TABLE public.aka_opd_registration ADD COLUMN IF NOT EXISTS follow_up text null;
ALTER TABLE public.aka_opd_registration ADD COLUMN IF NOT EXISTS follow_up_notes text null;
ALTER TABLE public.aka_opd_registration ADD COLUMN IF NOT EXISTS advice text null;
ALTER TABLE public.aka_opd_registration ADD COLUMN IF NOT EXISTS advice_rest boolean null default false;
ALTER TABLE public.aka_opd_registration ADD COLUMN IF NOT EXISTS advice_water boolean null default false;

-- 2. Create public.aka_refer_to table for doctor referral details
CREATE TABLE IF NOT EXISTS public.aka_refer_to (
  refer_id bigint generated by default as identity not null,
  registration_id bigint not null,
  patient_uhid text not null,
  doctor_name text not null,
  notes text null,
  created_date date not null default (timezone('Asia/Kolkata'::text, now()))::date,
  constraint aka_refer_to_pkey primary key (refer_id),
  constraint aka_refer_to_registration_id_fkey foreign key (registration_id) references public.aka_opd_registration (registration_id) on delete cascade,
  constraint aka_refer_to_patient_uhid_fkey foreign key (patient_uhid) references public.patient_detail (uhid) on delete cascade
) TABLESPACE pg_default;

-- Create indexes for faster lookups
CREATE INDEX IF NOT EXISTS idx_aka_refer_to_registration ON public.aka_refer_to (registration_id);
CREATE INDEX IF NOT EXISTS idx_aka_refer_to_patient_uhid ON public.aka_refer_to (patient_uhid);

-- 3. Create public.aka_procedure table for patient procedures suggested
CREATE TABLE IF NOT EXISTS public.aka_procedure (
  procedure_id bigint generated by default as identity not null,
  registration_id bigint not null,
  patient_uhid text not null,
  name text not null,
  duration text null,
  note text null,
  created_date date not null default (timezone('Asia/Kolkata'::text, now()))::date,
  constraint aka_procedure_pkey primary key (procedure_id),
  constraint aka_procedure_registration_id_fkey foreign key (registration_id) references public.aka_opd_registration (registration_id) on delete cascade,
  constraint aka_procedure_patient_uhid_fkey foreign key (patient_uhid) references public.patient_detail (uhid) on delete cascade
) TABLESPACE pg_default;

-- Create indexes for faster lookups
CREATE INDEX IF NOT EXISTS idx_aka_procedure_registration ON public.aka_procedure (registration_id);
CREATE INDEX IF NOT EXISTS idx_aka_procedure_patient_uhid ON public.aka_procedure (patient_uhid);
