-- Seeding script for Advice Templates (Category ID: 70)
-- Run this script in your Supabase SQL Editor to seed/update advices

-- 1. Ensure the Advice Templates category exists
INSERT INTO public.aka_dropdown_categories (id, code, display_name, allow_custom)
VALUES (70, 'advice_templates', 'Advice Templates', true)
ON CONFLICT (id) DO UPDATE 
SET code = EXCLUDED.code, display_name = EXCLUDED.display_name, allow_custom = EXCLUDED.allow_custom;

-- 2. Clear old advices in this category to prevent duplicates
DELETE FROM public.aka_master_dropdown_catalog WHERE category_id = 70;

-- 3. Seed new master advices
INSERT INTO public.aka_master_dropdown_catalog (category_id, value, usage_count)
VALUES
  (70, 'Avoid maida (eg: toast, butter, biscuit, Khari, cake, pav, bread)', 1),
  (70, 'Avoid exposure to excess light, sound, over work', 1),
  (70, 'Oil, ghee, maida, rice, sugar, red meat to be avoided', 1),
  (70, 'Avoid tea, coffee, tobacco, smoking, spicy food', 1),
  (70, 'Dinner 2 hr before going to lying down position', 1),
  (70, 'Propped up position while sleeping', 1),
  (70, 'Walk regularly for 30 minutes daily', 1),
  (70, 'Stop mobile phone use', 1),
  (70, 'Dietician reference', 1),
  (70, 'Weight reduction advised', 1),
  (70, 'Oral intake around 1-1.25 lt / day', 1),
  (70, 'Avoid folding knees, use English style lavatories', 1),
  (70, 'Salt restriction', 1),
  (70, 'Steam inhalation twice daily', 1),
  (70, 'Gargle with warm salt water', 1),
  (70, 'Avoid lifting heavy weights', 1),
  (70, 'Do not sit on the floor (cross-legged)', 1),
  (70, 'Use a hard mattress for sleeping', 1),
  (70, 'Drink at least 3-4 liters of water daily', 1),
  (70, 'Avoid spicy and oily food', 1),
  (70, 'Eat small and frequent meals', 1),
  (70, 'Do not skip breakfast', 1),
  (70, 'Avoid alcohol consumption', 1),
  (70, 'Quit smoking immediately', 1),
  (70, 'Monitor Blood Pressure daily', 1),
  (70, 'Check Blood Sugar Fasting and PP regularly', 1),
  (70, 'Apply ice pack on the affected area', 1),
  (70, 'Apply hot water bag fermentation', 1),
  (70, 'Elevate the affected limb while sleeping', 1),
  (70, 'Perform breathing exercises (Pranayama)', 1),
  (70, 'Avoid straining during stools', 1),
  (70, 'Include high fiber diet (green leafy vegetables, fruits)', 1),
  (70, 'Avoid pickles, papad, and processed foods', 1),
  (70, 'Rest your voice (Voice rest)', 1),
  (70, 'Wear loose and cotton clothes', 1),
  (70, 'Avoid direct exposure to AC or fan draft', 1),
  (70, 'Take medication after food only', 1),
  (70, 'Take medication on an empty stomach', 1),
  (70, 'Complete the full course of antibiotics', 1),
  (70, 'Do not self-medicate', 1),
  (70, 'Visit the dentist every 6 months', 1),
  (70, 'Brush teeth twice daily', 1),
  (70, 'Floss your teeth daily', 1),
  (70, 'Avoid sweets and sticky chocolates', 1),
  (70, 'Limit screen time (mobile/laptop)', 1),
  (70, 'Blink eyes frequently while working on screens', 1),
  (70, 'Wash eyes with cold water', 1),
  (70, 'Wear sunglasses when going out', 1),
  (70, 'Do not rub your eyes', 1),
  (70, 'Clean ears with a soft cloth, do not use earbuds', 1),
  (70, 'Keep the wound dry and clean', 1),
  (70, 'Change dressing daily', 1),
  (70, 'Do not scratch the rash or wound', 1),
  (70, 'Apply moisturizer immediately after bath', 1),
  (70, 'Use sunscreen with SPF 30+ daily', 1),
  (70, 'Trim nails regularly', 1),
  (70, 'Wash hands before and after meals', 1),
  (70, 'Boil and cool drinking water', 1),
  (70, 'Eat freshly cooked food only', 1),
  (70, 'Avoid street food and raw salads outside', 1),
  (70, 'Wash fruits and vegetables thoroughly before cooking', 1),
  (70, 'Include protein-rich food (dal, eggs, paneer, soya)', 1),
  (70, 'Avoid red meat and organ meats', 1),
  (70, 'Restrict fluid intake as advised', 1),
  (70, 'Measure urine output daily', 1),
  (70, 'Weigh yourself daily on an empty stomach', 1),
  (70, 'Perform Kegel exercises', 1),
  (70, 'Do ankle pumps exercise', 1),
  (70, 'Do quadriceps strengthening exercises', 1),
  (70, 'Wear a knee cap while walking', 1),
  (70, 'Use a walking stick for support', 1),
  (70, 'Wear comfortable footwear with soft soles', 1),
  (70, 'Avoid high heels', 1),
  (70, 'Do neck isometric exercises', 1),
  (70, 'Avoid prolonged neck bending (text neck)', 1),
  (70, 'Keep your back straight while sitting', 1),
  (70, 'Take breaks every 45 minutes while working', 1),
  (70, 'Perform spinal extension exercises', 1),
  (70, 'Sleep on your side with a pillow between knees', 1),
  (70, 'Avoid sleeping on your stomach', 1),
  (70, 'Breastfeed exclusively for 6 months', 1),
  (70, 'Burp the baby after every feed', 1),
  (70, 'Vaccinate the child as per schedule', 1),
  (70, 'Give Vitamin D3 drops as advised', 1),
  (70, 'Do not give honey or water to infants under 6 months', 1),
  (70, 'Maintain maintain genital hygiene', 1),
  (70, 'Change sanitary pads every 4-6 hours', 1),
  (70, 'Perform breast self-examination monthly', 1),
  (70, 'Taking Folic acid supplements is mandatory', 1),
  (70, 'Avoid papaya and pineapple during pregnancy', 1),
  (70, 'Sleep on the left lateral side during pregnancy', 1),
  (70, 'Monitor fetal movements', 1),
  (70, 'Avoid travel in the first and last trimester', 1),
  (70, 'Start complimentary feeding at 6 months', 1),
  (70, 'Avoid bottle feeding', 1),
  (70, 'Use a spoon and bowl for feeding baby', 1),
  (70, 'Massage the baby daily', 1),
  (70, 'Expose the baby to mild morning sunlight', 1),
  (70, 'Isolate the patient in a separate room', 1),
  (70, 'Wear a mask when around others', 1),
  (70, 'Sanitize surfaces frequently', 1),
  (70, 'Dispose of tissues properly', 1),
  (70, 'Cover mouth while coughing or sneezing', 1),
  (70, 'Monitor oxygen saturation (SpO2)', 1),
  (70, 'Monitor temperature every 6 hours', 1),
  (70, 'Tepid sponging for high fever', 1),
  (70, 'Drink ORS solution for dehydration', 1),
  (70, 'Drink coconut water and buttermilk', 1),
  (70, 'Avoid carbonated drinks and sodas', 1),
  (70, 'Avoid caffeine (excess tea/coffee)', 1),
  (70, 'Avoid bakery products completely', 1),
  (70, 'Avoid deep-fried snacks (samosa, vada)', 1),
  (70, 'Eat dinner by 8:00 PM', 1),
  (70, 'Chew your food properly', 1),
  (70, 'Do not lie down immediately after eating', 1),
  (70, 'Go for a short walk after dinner', 1),
  (70, 'Avoid late-night snacking', 1),
  (70, 'Practice meditation for stress relief', 1),
  (70, 'Get at least 7-8 hours of sleep', 1),
  (70, 'Maintain a regular sleep schedule', 1),
  (70, 'Avoid bright lights before bedtime', 1),
  (70, 'Drink a glass of warm milk before sleep', 1),
  (70, 'Avoid fruits at night', 1),
  (70, 'Avoid curd/yogurt at night', 1),
  (70, 'Eat seasonal fruits and vegetables', 1),
  (70, 'Avoid shelf-stable/packaged foods', 1),
  (70, 'Limit salt intake to 1 tsp per day', 1),
  (70, 'Use rock salt instead of table salt', 1),
  (70, 'Avoid adding extra salt to cooked food', 1),
  (70, 'Soak nuts (almonds/walnuts) overnight before eating', 1),
  (70, 'Include turmeric and ginger in diet', 1),
  (70, 'Drink warm lemon water with honey', 1),
  (70, 'Avoid chilled water from the fridge', 1),
  (70, 'Do not share personal items (towels, combs)', 1),
  (70, 'Wash clothes in hot water', 1),
  (70, 'Sun-dry clothes properly', 1),
  (70, 'Keep the house dust-free', 1),
  (70, 'Avoid carpets and soft toys if allergic', 1),
  (70, 'Use anti-dust mite pillow covers', 1),
  (70, 'Keep pets out of the bedroom', 1),
  (70, 'Avoid strong perfumes and agarbatti smoke', 1),
  (70, 'Wear a lumbar corset belt while traveling', 1),
  (70, 'Wear a cervical collar as advised', 1),
  (70, 'Use a heating pad for back pain', 1),
  (70, 'Do simple stretching exercises daily', 1),
  (70, 'Join a yoga class', 1),
  (70, 'Practice deep breathing', 1),
  (70, 'Laugh loudly (Laughter therapy)', 1),
  (70, 'Socialize with friends and family', 1),
  (70, 'Keep a positive mindset', 1),
  (70, 'Follow up after 3 days', 1),
  (70, 'Report immediately if symptoms worsen', 1),
  (70, 'Bring old reports during the next visit', 1),
  (70, 'Keep a file of all medical records', 1),
  (70, 'Check expiry dates of medicines', 1),
  (70, 'Store medicines in a cool, dry place', 1),
  (70, 'Keep medicines out of reach of children', 1),
  (70, 'Shake the syrup bottle well before use', 1),
  (70, 'Use the measuring cup provided with syrup', 1),
  (70, 'Do not crush or break tablets unless advised', 1),
  (70, 'Dissolve the tablet in water before taking', 1),
  (70, 'Place the tablet under the tongue (Sublingual)', 1),
  (70, 'Inhale the rotacap/inhaler deeply', 1),
  (70, 'Rinse mouth after using an inhaler', 1),
  (70, 'Apply ointment vertically not circularly', 1),
  (70, 'Massage the oil gently', 1),
  (70, 'Do not massage on open wounds', 1),
  (70, 'Apply pressure on the injection site', 1),
  (70, 'Rotate insulin injection sites', 1),
  (70, 'Keep insulin in the refrigerator door', 1),
  (70, 'Carry sugar/candy for hypoglycemia', 1),
  (70, 'Wear a medical ID bracelet', 1),
  (70, 'Inform the doctor about allergies', 1),
  (70, 'Inform the doctor if you are pregnant', 1),
  (70, 'Inform the doctor if you are breastfeeding', 1),
  (70, 'Discuss side effects of medicines', 1),
  (70, 'Do not stop medication abruptly', 1),
  (70, 'Taper the dose as advised', 1),
  (70, 'Avoid driving if feeling dizzy', 1),
  (70, 'Avoid operating heavy machinery', 1),
  (70, 'Use earplugs in noisy environments', 1),
  (70, 'Get your hearing tested', 1),
  (70, 'Get your vision checked annually', 1),
  (70, 'Use lubricating eye drops', 1),
  (70, 'Avoid contact lenses during infection', 1),
  (70, 'Clean contact lenses solution daily', 1),
  (70, 'Do not sleep with contact lenses on', 1),
  (70, 'Avoid kajal/surma in eyes', 1),
  (70, 'Clean the tongue daily', 1),
  (70, 'Replace toothbrush every 3 months', 1),
  (70, 'Use a soft-bristled toothbrush', 1),
  (70, 'Avoid grinding teeth', 1),
  (70, 'Wear a night guard if advised', 1),
  (70, 'Avoid very hot or very cold foods', 1),
  (70, 'Chew from both sides of the mouth', 1),
  (70, 'Avoid chewing tobacco/pan masala', 1),
  (70, 'Gargle with betadine mouthwash', 1),
  (70, 'Use antiseptic soap for bathing', 1),
  (70, 'Pat dry skin, do not rub hard', 1),
  (70, 'Apply powder in fungal infection areas', 1),
  (70, 'Wear breathable cotton socks', 1),
  (70, 'Change socks daily', 1),
  (70, 'Air out shoes regularly', 1),
  (70, 'Do not walk barefoot', 1),
  (70, 'Check feet daily for cuts (Diabetics)', 1),
  (70, 'Cut nails straight across', 1),
  (70, 'File the corners of nails', 1),
  (70, 'Do not cut corns or calluses yourself', 1),
  (70, 'Moisturize heels to prevent cracks', 1),
  (70, 'Use a pumice stone gently', 1),
  (70, 'Soak feet in warm salt water', 1),
  (70, 'Elevate legs to reduce swelling', 1),
  (70, 'Wear compression stockings', 1),
  (70, 'Avoid standing for long hours', 1),
  (70, 'Move your toes while sitting', 1),
  (70, 'Take micro-breaks from sitting', 1),
  (70, 'Use a standing desk if possible', 1),
  (70, 'Adjust chair height correctly', 1),
  (70, 'Keep the monitor at eye level', 1),
  (70, 'Use an ergonomic keyboard/mouse', 1),
  (70, 'Support your lower back while sitting', 1),
  (70, 'Avoid crossing legs while sitting', 1),
  (70, 'Get up and stretch every hour', 1),
  (70, 'Drink water before meals', 1),
  (70, 'Avoid drinking water during meals', 1),
  (70, 'Drink water 30 mins after meals', 1),
  (70, 'Drink warm water for digestion', 1),
  (70, 'Eat curd or probiotics daily', 1),
  (70, 'Drink buttermilk after lunch', 1),
  (70, 'Avoid raw seafood', 1),
  (70, 'Cook meat thoroughly', 1),
  (70, 'Avoid leftovers older than 24 hours', 1),
  (70, 'Reheat food properly before eating', 1),
  (70, 'Store food in airtight containers', 1),
  (70, 'Check food labels for ingredients', 1),
  (70, 'Avoid food with MSG (Ajinomoto)', 1),
  (70, 'Avoid artificial sweeteners', 1),
  (70, 'Limit intake of refined sugar', 1),
  (70, 'Use jaggery or honey instead of sugar', 1),
  (70, 'Eat whole grains (Brown rice, oats)', 1),
  (70, 'Eat multi-grain roti/chapati', 1),
  (70, 'Mix bajra/jowar flour with wheat', 1),
  (70, 'Eat sprouts and pulses', 1),
  (70, 'Soak pulses before cooking', 1),
  (70, 'Use healthy oils (Olive, Mustard, Bran)', 1),
  (70, 'Rotate cooking oils', 1),
  (70, 'Do not reuse frying oil', 1),
  (70, 'Limit intake of butter and cheese', 1),
  (70, 'Choose low-fat milk options', 1),
  (70, 'Eat handful of nuts daily', 1),
  (70, 'Eat flaxseeds and chia seeds', 1),
  (70, 'Eat fatty fish (Salmon/Mackerel) twice a week', 1),
  (70, 'Include garlic and onion in diet', 1),
  (70, 'Drink green tea', 1),
  (70, 'Avoid energy drinks', 1),
  (70, 'Limit fruit juices (eat whole fruit)', 1),
  (70, 'Avoid sugary sodas', 1),
  (70, 'Drink herbal tea (Tulsi/Ginger)', 1),
  (70, 'Do regular full body checkups', 1),
  (70, 'Get lipid profile checked', 1),
  (70, 'Get thyroid function test done', 1),
  (70, 'Check liver function test', 1),
  (70, 'Check kidney function test', 1),
  (70, 'Check Vitamin B12 and D3 levels', 1),
  (70, 'Screen for cervical cancer (Pap smear)', 1),
  (70, 'Screen for prostate cancer (PSA)', 1),
  (70, 'Screen for breast cancer (Mammography)', 1),
  (70, 'Monitor BMI (Body Mass Index)', 1),
  (70, 'Maintain a healthy waist circumference', 1),
  (70, 'Focus on belly fat reduction', 1),
  (70, 'Do aerobic exercises (Swimming/Cycling)', 1),
  (70, 'Do strength training twice a week', 1),
  (70, 'Start with warm-up exercises', 1),
  (70, 'End with cool-down stretches', 1),
  (70, 'Listen to your body, do not overexert', 1),
  (70, 'Stay hydrated during exercise', 1),
  (70, 'Wear proper gym gear', 1),
  (70, 'Consult a physiotherapist for pain', 1),
  (70, 'Follow the R.I.C.E. protocol for injuries', 1),
  (70, 'Rest the injured part', 1),
  (70, 'Compress with a bandage', 1),
  (70, 'Protect the injury from further harm', 1),
  (70, 'Do balance exercises (Stand on one leg)', 1),
  (70, 'Practice Tai Chi or Yoga', 1),
  (70, 'Improve your posture', 1),
  (70, 'Stand tall with shoulders back', 1),
  (70, 'Do not slouch', 1),
  (70, 'Use a headset for long calls', 1),
  (70, 'Do not cradle phone between ear and shoulder', 1),
  (70, 'Manage anger and anxiety', 1),
  (70, 'Seek counseling if depressed', 1),
  (70, 'Join a support group', 1),
  (70, 'Practice mindfulness', 1),
  (70, 'Spend time in nature', 1),
  (70, 'Get sunlight exposure (Vitamin D)', 1),
  (70, 'Keep indoor plants for fresh air', 1),
  (70, 'Ensure proper ventilation in home', 1),
  (70, 'Use a humidifier in dry weather', 1),
  (70, 'Use a mosquito net or repellent', 1),
  (70, 'Eliminate standing water (Dengue prev)', 1),
  (70, 'Wear full-sleeved clothes in evening', 1),
  (70, 'Use coils or vaporizers with caution', 1),
  (70, 'Keep bathrooms clean and dry', 1),
  (70, 'Install grab bars in bathroom (Elderly)', 1),
  (70, 'Use anti-slip mats in bathroom', 1),
  (70, 'Ensure good lighting in the house', 1),
  (70, 'Remove tripping hazards (rugs/wires)', 1),
  (70, 'Keep a torch/flashlight handy', 1),
  (70, 'Keep emergency numbers saved', 1),
  (70, 'Learn CPR (Cardiopulmonary Resuscitation)', 1),
  (70, 'Keep a First Aid kit ready', 1),
  (70, 'Learn the Heimlich maneuver', 1),
  (70, 'Know the signs of stroke (FAST)', 1),
  (70, 'Know the signs of heart attack', 1),
  (70, 'Seek immediate help for chest pain', 1),
  (70, 'Do not ignore severe headaches', 1),
  (70, 'Report sudden vision loss', 1),
  (70, 'Report difficulty in speaking', 1),
  (70, 'Report weakness in limbs', 1),
  (70, 'Report blood in urine or stool', 1),
  (70, 'Report unexplained weight loss', 1),
  (70, 'Report persistent cough', 1),
  (70, 'Report lumps or swellings', 1),
  (70, 'Report change in mole size/color', 1),
  (70, 'Report non-healing ulcers', 1),
  (70, 'Avoid self-diagnosis on the internet', 1),
  (70, 'Trust your doctor''s advice', 1),
  (70, 'Ask questions if you don''t understand', 1),
  (70, 'Bring a family member for support', 1),
  (70, 'Be honest about your lifestyle', 1),
  (70, 'Follow the discharge summary instructions', 1),
  (70, 'Schedule follow-up appointments', 1),
  (70, 'Adhere to the prescribed diet chart', 1),
  (70, 'Take part in vaccination drives', 1),
  (70, 'Donate blood if eligible', 1),
  (70, 'Register for organ donation', 1),
  (70, 'Avoid mango, custard apple, cheeku (for Diabetics)', 1),
  (70, 'Avoid underground vegetables (potato, yam) if advised', 1),
  (70, 'Restrict potassium rich foods (banana, coconut water) in renal failure', 1),
  (70, 'Avoid besan (gram flour) items for gas trouble', 1),
  (70, 'Eat early dinner for digestion', 1),
  (70, 'Avoid drinking tea on empty stomach', 1),
  (70, 'Soak coriander seeds water for thyroid', 1),
  (70, 'Drink methi (fenugreek) water for diabetes', 1),
  (70, 'Eat roasted chana for protein', 1),
  (70, 'Consume jaggery and peanuts for hemoglobin', 1),
  (70, 'Use iron skillet for cooking', 1),
  (70, 'Avoid aluminum cookware', 1),
  (70, 'Use clay pots for cooking', 1),
  (70, 'Do not reheat tea', 1),
  (70, 'Avoid eating stale rice', 1),
  (70, 'Consume buttermilk with cumin powder', 1),
  (70, 'Eat curd rice for stomach upset', 1),
  (70, 'Drink rice kanji (water) during diarrhea', 1),
  (70, 'Eat khichdi for light digestion', 1),
  (70, 'Avoid sabudana during weight loss', 1),
  (70, 'Eat oats or daliya for breakfast', 1),
  (70, 'Replace sugar with stevia if diabetic', 1),
  (70, 'Avoid artificial colors in food', 1),
  (70, 'Wash hands after touching pets', 1),
  (70, 'Deworm pets regularly', 1),
  (70, 'Deworm yourself and family every 6 months', 1),
  (70, 'Avoid barefoot walking in soil', 1),
  (70, 'Wash feet before entering bed', 1),
  (70, 'Change bedsheets weekly', 1),
  (70, 'Sun-dry mattresses periodically', 1),
  (70, 'Vacuum clean upholstery', 1),
  (70, 'Clean AC filters monthly', 1),
  (70, 'Service water purifiers regularly', 1),
  (70, 'Check gas leakages immediately', 1),
  (70, 'Keep bathroom door closed', 1),
  (70, 'Do not hold urine for long', 1),
  (70, 'Pass urine after sexual intercourse', 1),
  (70, 'Wash private parts from front to back', 1),
  (70, 'Avoid using scented hygiene products', 1),
  (70, 'Wear cotton underwear', 1),
  (70, 'Change underwear daily', 1),
  (70, 'Avoid tight jeans or trousers', 1),
  (70, 'Wash new clothes before wearing', 1),
  (70, 'Avoid sharing makeup', 1),
  (70, 'Discard old makeup products', 1),
  (70, 'Clean makeup brushes regular', 1),
  (70, 'Remove makeup before sleeping', 1),
  (70, 'Apply night cream', 1),
  (70, 'Use lip balm for dry lips', 1),
  (70, 'Do not peel dry skin on lips', 1),
  (70, 'Avoid licking lips', 1),
  (70, 'Stay calm and relaxed', 1),
  (70, 'Deep breathing in fresh air', 1),
  (70, 'Avoid crowds during flu season', 1),
  (70, 'Avoid shaking hands during outbreaks', 1),
  (70, 'Use ''Namaste'' greeting', 1),
  (70, 'Carry a hand sanitizer', 1),
  (70, 'Sanitize phone and keys daily', 1);
