-- SQL script to insert diagnoses suggestions into public.aka_master_dropdown_catalog
-- Category 8 represents Diagnosis suggestions.
-- Only inserts values if they do not already exist in the database (case-insensitive check).

INSERT INTO public.aka_master_dropdown_catalog (category_id, value, usage_count)
SELECT 8, val, 1
FROM (
  VALUES
    ('Diabetes mellitus type 2'),
    ('HT - Hypertension'),
    ('IHD - Ischemic heart disease'),
    ('Hypothyroid'),
    ('Migraine'),
    ('PN - Peripheral neuropathy'),
    ('Anemia'),
    ('CKD - Chronic Kidney Disease'),
    ('GAD - Generalised anxiety disorder'),
    ('CVA - Cerebrovascular accident'),
    ('COPD - Chronic Obstructive Pulmonary Disease'),
    ('IBS - Irritable bowel syndrome'),
    ('OA - Osteoarthritis of knee'),
    ('UTI - Urinary Tract Infection'),
    ('CHF - Congestive heart failure'),
    ('Pulmonary Tuberculosis'),
    ('Osteoporosis'),
    ('GAD - Generalized anxiety disorder'),
    ('URTI Upper Respiratory Tract Infection'),
    ('Vitamin D3 Deficiency'),
    ('Hypothyroidism'),
    ('OSAHS - Obstructive Sleep Apnea-Hypopnea Syndrome'),
    ('Obstructive Airway Disease'),
    ('BPH - benign prostatic hypertrophy'),
    ('LRTI Lower respiratory tract infection'),
    ('BPPV - Benign paroxysmal positional vertigo'),
    ('Hhd vs ihd'),
    ('Left frozen shoulder'),
    ('GERD - Gastro-esophageal reflux disease'),
    ('AKI - Acute kidney injury'),
    ('Hyperthyroidism'),
    ('Aki vs ckd'),
    ('Acute infective bronchitis'),
    ('Acute Gastroenteritis AGE'),
    ('HTN - Hypertension'),
    ('Extrapulmonary Tuberculosis'),
    ('Acute exacerbation of chronic obstructive airways disease'),
    ('Obesity'),
    ('Acute exacerbation of COPD (Chronic Obstructive Airways Disease)'),
    ('DCM - Dilated cardiomyopathy'),
    ('Dyslipidemia'),
    ('RhA - Rheumatoid arthritis'),
    ('Secondary hypoaldosteronism'),
    ('Pyelonephritis'),
    ('Parkinsons disease'),
    ('Osteopenia'),
    ('Herpes zoster infection'),
    ('Inflammatory arthritis'),
    ('HHD - Hypertensive heart disease'),
    ('Convulsion disorder'),
    ('Panic Disorder'),
    ('Right frozen shoulder'),
    ('ILD - Interstitial Lung Disease'),
    ('Cellulitis of leg'),
    ('E.d'),
    ('DM - Diabetes mellitus'),
    ('Vivax malaria'),
    ('Doe unber evaluation'),
    ('Significant post void volume'),
    ('Hyperuricemia'),
    ('Abdominal kochs'),
    ('Reactive Arthritis'),
    ('Umbilical Hernia'),
    ('Urosepsis'),
    ('Right bells palsy'),
    ('Morbid Obesity'),
    ('Pneumonitis'),
    ('Hyperactive bladder'),
    ('Musculoskeletal pain disorder'),
    ('Dengue Fever'),
    ('Iron deficiency anemias'),
    ('Left upper limb radiculopathy'),
    ('DVT - Deep venous thrombosis of leg'),
    ('Gastritis'),
    ('Aki on ckd'),
    ('Carcinoma of breast'),
    ('Retrovirus infection'),
    ('Convulsions'),
    ('PVD-peripheral vascular disease'),
    ('AF - Atrial fibrillation'),
    ('Chronic atrial fibrillation'),
    ('Liver abcess'),
    ('Potts spin'),
    ('Acute Cholecystitis'),
    ('Gouty arthritis'),
    ('Acute Pancreatitis'),
    ('Depression'),
    ('Enteric Fever'),
    ('Diplopia'),
    ('GDM - Gestational diabetes mellitus'),
    ('H Pylori Infection'),
    ('Severe PAH - (Pulmonary Arterial Hypertension)'),
    ('Psychosis'),
    ('Bodyache under evaluation'),
    ('PAH - Pulmonary Arterial Hypertension'),
    ('Hyponatremia'),
    ('Cbd calculus'),
    ('RHD - Rheumatic Heart Disease'),
    ('Sero positive'),
    ('Varicose Veins'),
    ('Left lower limb radiculopathy'),
    ('Pancreatitis'),
    ('Post nephrectomy status'),
    ('PIH - Pregnancy-induced hypertension'),
    ('Cerebral venous sinus thrombosis'),
    ('Cholelithiasis'),
    ('Ihd vs osa'),
    ('Splenic abscess'),
    ('Post cataract surgery status'),
    ('Subacute intestinal obstruction NOS'),
    ('Osteopenia vs osteoporosis'),
    ('Action tremors'),
    ('Pedal Edema'),
    ('GI bleeding'),
    ('Costochondritis'),
    ('Ankylosing spondylitis'),
    ('Right sided small kidney'),
    ('Fibrotic lung'),
    ('Giddiness'),
    ('Allergic'),
    ('Anxiety disorders'),
    ('Viral Hepatitis'),
    ('ACS - Acute coronary syndrome'),
    ('Left thoracic radiculopathy'),
    ('Urticaria'),
    ('Bilateral lower limb odema'),
    ('Hypertensive ic bleed'),
    ('MDR PTB - Multidrug-Resistant Pulmonary Tuberculosis'),
    ('Post hernioplasty status'),
    ('Left sided bell''s palsy'),
    ('Post turp status'),
    ('Post viral pneumonitis'),
    ('Menorrhagia'),
    ('Hypoglycemia'),
    ('Renal Calculus'),
    ('viral pneumonitis'),
    ('Had taken unlabelled medication for arthritis'),
    ('Lumbar Canal Stenosis'),
    ('Sepsis'),
    ('Right lower limb radiculopathy'),
    ('Post hysterectomy status'),
    ('Post left knee replacement'),
    ('Accelerated essential hypertension'),
    ('Seronegative Arthritis'),
    ('Aortic stenosis'),
    ('Right lower ureteric calculus'),
    ('Frozen shoulder'),
    ('Rash under evaluation'),
    ('Psychiatric disorder'),
    ('Degenerative brain disorder'),
    ('Proximal Humerus Fracture'),
    ('Att induce hepatitis'),
    ('Bmd'),
    ('CHB - Complete heart block'),
    ('Compression fracture of vertebral column'),
    ('Right upper limb radiculopathy'),
    ('Fluid Overload'),
    ('Pseudo seizure vs seizure'),
    ('TN - Trigeminal neuralgia'),
    ('Local cellulittis'),
    ('Parkinsonism'),
    ('Constipation'),
    ('Right thoracic radiculopathy'),
    ('Grade 2 diastolic dysfunction'),
    ('Hcv'),
    ('Colonic diverticulosis'),
    ('Oral Candidiasis'),
    ('Oesophageal web'),
    ('Left renal calculus'),
    ('Psoriasis'),
    ('Chronic cystitis'),
    ('Tuberculoma'),
    ('Obstructive Jaundice'),
    ('Migrane'),
    ('Past history of pul kochs'),
    ('ITP - idiopathic thrombocytopenic purpura'),
    ('Subcutaneous lipoma'),
    ('Right lumbar radiculopathy'),
    ('Fatty Liver'),
    ('Hbsag positive'),
    ('Beta thalassemia trait'),
    ('Lower back pain under evaluation'),
    ('Recurrent UTI - urinary tract infection'),
    ('Acute pyelonephritis'),
    ('Low ejection fraction'),
    ('Encephalitis'),
    ('Left sideed radiculopathy'),
    ('Miliary Tuberculosis'),
    ('Moderate pulmonary hypertension'),
    ('Left hydronephrosis with calculus'),
    ('Hypersensitivity Pneumonitis'),
    ('ASD - Atrial septal defect'),
    ('SAH - Subarachnoid hemorrhage'),
    ('Angio odema'),
    ('IBD - Inflammatory bowel disease'),
    ('AVN - Avascular necrosis of bone'),
    ('Proteinuria'),
    ('Chronic fatigue syndrome'),
    ('Cellulitis of left upper limb'),
    ('Glaucoma'),
    ('Past history of extra pulmonary kochs'),
    ('Ihd vs anemia'),
    ('Hyperprolactinemia'),
    ('Folitrax induced oral ulcer'),
    ('Radiculopathy'),
    ('Sever mr'),
    ('Acute lacunar infarction'),
    ('Meningitis'),
    ('RTA'),
    ('Post mitral valve replacemet'),
    ('ca gall bladder'),
    ('Involuntary movement disorder'),
    ('Hypertensive nephropathy'),
    ('5mth ammenorhea'),
    ('Reproductive track infection'),
    ('SLE - Systemic lupus erythematosus'),
    ('Bleeding Per Rectum'),
    ('Left non obstructive renal calculus'),
    ('Impaired hearing'),
    ('Right 2 finger cellulitis'),
    ('Right leg cellulitis'),
    ('Att induce gastritis'),
    ('Fissure'),
    ('Chronic uti'),
    ('CTS - Carpal tunnel syndrome'),
    ('Hook worm infestation'),
    ('Bradykinesia'),
    ('Right sided Pneumonia'),
    ('Afi under evaluation'),
    ('Tender periareolar area'),
    ('History of exposure to some umn labelled medication'),
    ('Bladder Calculus'),
    ('SVT - Supraventricular tachycardia'),
    ('Cervical lymphadnitis'),
    ('Cag wnl'),
    ('Bradycardia'),
    ('History of alcohol intake'),
    ('Nephropathy - diabetic'),
    ('Bening mass in brain meningioma'),
    ('Dysnea'),
    ('Helicobacter pylori-associated gastritis'),
    ('Obstructive uropathy'),
    ('Past h/o pulumonary kochs'),
    ('Tuberculous Cervical Lymphadenitis'),
    ('Renal Cell Carcinoma'),
    ('Convulsion vs syncope'),
    ('Right hemiparesis'),
    ('Lung carcinoma'),
    ('Tia vs neuropathy'),
    ('Grade hydrocele'),
    ('Post hip replacement'),
    ('Syncope vs partial convulsion'),
    ('Mod pah'),
    ('Accelerated hypertension'),
    ('Recurrent sinusitis'),
    ('Malaria by Plasmodium vivax'),
    ('GTCS - Generalized Tonic Clonic Seizure'),
    ('Nephrotic range proteinurea under evaluation'),
    ('Left 4 th nerve involvement'),
    ('DCLD - Decompensated chronic liver disease'),
    ('Diabetes in pregnancy'),
    ('Right hemiplegia'),
    ('Palpittion under evaluation'),
    ('Wedge Compression Fracture'),
    ('Chronic cerebral ischemia'),
    ('Dementia'),
    ('Eosinophilic colitis'),
    ('Tuberculosis of spine (Pott''s)'),
    ('Thrombocytopenia'),
    ('Pre diabetic'),
    ('Falciparum malaria'),
    ('OCD - Obsessive-compulsive disorder'),
    ('Left lower lobe pneumonitis'),
    ('Post uretero vesicle plasty'),
    ('Cholecystectomy'),
    ('Post lap cholecystectomy'),
    ('Pulmonary thromboembolism'),
    ('Panic Attack'),
    ('CML - Chronic myeloid leukemia'),
    ('Saccular aneurysm'),
    ('Right upper limb venous thrombosis'),
    ('Recurrent pulmonary kochs'),
    ('AWMI-Anterior Wall Myocardial Infarction'),
    ('Polycystic Kidney Disease'),
    ('Left bells palsy'),
    ('Lung maas'),
    ('Carpal Tunnel Syndrome'),
    ('Left lumbar radiculopathy'),
    ('Headache under evaluation'),
    ('Tia vs conversion disorder'),
    ('Bilateral inguinal hernia'),
    ('Moderate mr with mod pah'),
    ('Cellulitis of thigh'),
    ('TIA - Transient ischaemic attack'),
    ('Second degree heart block'),
    ('Scar Epilepsy'),
    ('SDH - Subdural hematoma'),
    ('Hiatus Hernia'),
    ('Left mid brain infarct'),
    ('Chronic loosmotion'),
    ('CA - Breast cancer'),
    ('Megaloblastic anemia'),
    ('On psychiatry rx wth some other dr'),
    ('Left upper limb radiculopathy vs ihl'),
    ('Lung abcess'),
    ('O .a'),
    ('Crao'),
    ('GAVE - Gastric antral vascular ectasia'),
    ('Palpitation'),
    ('Past history of viral pneumonitis'),
    ('On new bona since 8/2/24'),
    ('Fibrosed lung'),
    ('APKD - Adult type polycystic disease'),
    ('Left sided facial palsy'),
    ('CSOM - Chronic suppurative otitis media'),
    ('Right lateral rectus palsy'),
    ('Primary hypoaldosteronism'),
    ('Vulval abscess'),
    ('Septic Shock'),
    ('Metabolic Syndrome'),
    ('Celiac disease'),
    ('Functional disorder'),
    ('Orthostatic hypotension'),
    ('Viral infectious hepatitis A'),
    ('Pulmonary Embolism'),
    ('Hypokalemia'),
    ('Vitamin D Deficiency'),
    ('Tuberculoma of brain'),
    ('Bronchitis - acute'),
    ('Obstructive airway disease vs anxiety'),
    ('NAFLD - Nonalcoholic fatty liver disease'),
    ('Low ef under evaluation'),
    ('Pain in abdomen under evaluation'),
    ('Left lateral rectus palsy'),
    ('Fever with rash'),
    ('Holter s/o supra ventricular ectopics'),
    ('Acute febrile illness'),
    ('Nephrotic syndrome'),
    ('Superficial thrombophlebitis of leg'),
    ('DKA - Diabetic ketoacidosis'),
    ('Cardiorenal syndrome'),
    ('LVF - Left ventricular failure'),
    ('Lumbar radiculopathy'),
    ('Oesophageal stenosis'),
    ('Chf'),
    ('Gynacomastia'),
    ('Mitral commissurectomy'),
    ('History of lymhoma'),
    ('Polyp of gallbladder'),
    ('Pancytopenia'),
    ('Right renal calculus'),
    ('Pregnancy'),
    ('R mca teritory infarct'),
    ('Sever anemia'),
    ('Insomnia'),
    ('Space occuping lesion'),
    ('Polycythemia vera'),
    ('Post pace maker status'),
    ('Low back pain'),
    ('Uveitis'),
    ('Ilius vs acute cholecystitis'),
    ('Sjogrens Syndrome'),
    ('Pedal odema under evaluation'),
    ('Lrti vs reactivation'),
    ('Ascites'),
    ('Subclinical hypothyroidism'),
    ('Beta thalassemia: (& minor)'),
    ('Cataract'),
    ('Bed sore'),
    ('Jaundice'),
    ('Protein-losing nephropathy'),
    ('Gad vs ihd'),
    ('K/c/o bipolar disorder'),
    ('Bilateral small kidneys'),
    ('Ulcerative Colitis'),
    ('Chronic cough under evaluation'),
    ('Past h/o abdominal kochs'),
    ('Myocardial bridge of coronary artery'),
    ('Bronchieactasis'),
    ('@relative'),
    ('Pneumothorax'),
    ('Gerd vs ibs'),
    ('Left sided pleural effusion under evaluation'),
    ('6 mth ammenorhea'),
    ('Exophthalmos'),
    ('Diabetic Foot'),
    ('Warthin tumour'),
    ('Increased frequency of urine under evaluation'),
    ('HFPEF - Heart failure with preserved ejection fraction'),
    ('Uremic encephalopathy'),
    ('Allergic bronchitis'),
    ('3 mth ammenorhea'),
    ('Fracture 3rd toes'),
    ('Hemmorhoids'),
    ('7 mth ammenorhea'),
    ('Left 3rd nerve palsy'),
    ('Dermatitis'),
    ('Neuralgia'),
    ('History of unlabelled medicine intake'),
    ('Poor ef'),
    ('K /c/o convulsion disorder'),
    ('Enterocolitis'),
    ('Left wrist fracture'),
    ('Apla syndrome'),
    ('Epistaxis'),
    ('2 mth ammenorhoea'),
    ('Nsvt'),
    ('Third nerve palsy'),
    ('Nasal bleed'),
    ('Bilateral Pedal odema'),
    ('Arachnoid cyst'),
    ('Breathlessness under evaluation'),
    ('Past history of herpes zoster same dermatome'),
    ('Retinal detachment'),
    ('Carbuncle of neck'),
    ('Psoriatic arthritis'),
    ('Imblance under evaluation'),
    ('Acute anterior uveitis'),
    ('Right inguinal hernia'),
    ('Cellulitis of right lower limb'),
    ('Post pcnl status'),
    ('Syncope'),
    ('Giddines under evalation'),
    ('Carcinoma of Colon'),
    ('Diverticulitis of colon'),
    ('Moderate ms'),
    ('Thromocytopenia'),
    ('Ca left breast'),
    ('History of un monitored steroid'),
    ('Mixed connective tissue disease'),
    ('Hereditary thrombocytopenia'),
    ('Bladder mass under evaluation'),
    ('Loose Motion'),
    ('Lymphoma'),
    ('Carcinoma of buccal mucosa'),
    ('TMJPDS - Temporomandibular joint pain dysfunction syndrome'),
    ('Dengue shock syndrome'),
    ('Local abcess'),
    ('Penile lesion'),
    ('Asthama'),
    ('Drug induce peripheral neuropathy'),
    ('Cavitatory lesionof lung under evaluation'),
    ('CABG - Coronary artery bypass grafting'),
    ('Keloid'),
    ('Right side moderate hydronephrosis'),
    ('Patient was on unlabelled medication for arthritis'),
    ('Hyper tensive i.c. Bleed'),
    ('History of itp in child hood'),
    ('Moderate sleep apnea'),
    ('Accesary breast'),
    ('5 mth ammenorhea'),
    ('Beningn thrombocytopenia'),
    ('Fungal Infection'),
    ('Hepatic encephalopathy'),
    ('GBS - Guillain-Barre syndrome'),
    ('Hydronephrosis'),
    ('Sub acute intra cranial hemorrhage'),
    ('Urinary incontinence'),
    ('Post perforated appendix'),
    ('Lrti vs chf'),
    ('Chickenpox - varicella'),
    ('Sudden onset giddnes query syncope'),
    ('Chest pain under evaluation'),
    ('Plan for cataract sx'),
    ('Left lower back radiculopathy'),
    ('Left Hemiparesis'),
    ('Sinusitis'),
    ('Soar throat'),
    ('Diabetic autonomic neuropathy'),
    ('Type1 Diabetes Mellitus'),
    ('Was taking unlabelled medication'),
    ('Afi with tcp'),
    ('Oesophageal candidiasis'),
    ('Osteopetrosis'),
    ('Gb calculus'),
    ('Right inguinal lymphadenitis'),
    ('Pan Gastritis'),
    ('Sleep apnea mod intensity'),
    ('Chronic Liver Disease'),
    ('Collapse compression fracture t12,l1 vertebrae'),
    ('On DAT since 6 yr'),
    ('Obstructive airway disease vs chf'),
    ('Perforated left ear drum'),
    ('Post dual valve replacement'),
    ('Cag was done in past came normal'),
    ('Hyperhomocysteinemia'),
    ('Fasiculation'),
    ('Left local cellulitis around t m joint'),
    ('High hemoglobin under evaluation'),
    ('Tremors of head'),
    ('Convulsion disorder on antiepileptic'),
    ('B/l oophorectomy'),
    ('Meningoencephalitis'),
    ('Viral afi'),
    ('Had one episodeof stiffness of left upper limb andlower limb'),
    ('B12 deficiency anemia'),
    ('Cbd dialted on usg'),
    ('Varicocele'),
    ('Atypical Chest Pain'),
    ('Post sepsis status'),
    ('Recurent pancreatitiss'),
    ('Bilater renal calculus'),
    ('Dynamic Suggestions'),
    ('Post axilary lymph node excision status'),
    ('Sebaceous Cyst'),
    ('Hla b27'),
    ('6 wk ammenorhea'),
    ('Varicella'),
    ('Ataxia under evaluation'),
    ('Incisional hernia'),
    ('Left ureteric calculus'),
    ('Multi lumbar area indentation'),
    ('Global hypokinesia'),
    ('Uremia'),
    ('Acute gastritis'),
    ('Acs vs gad'),
    ('Gerd vs gad'),
    ('Congenital heart disease'),
    ('Change of voice'),
    ('Left lower limb cellulitis'),
    ('ARDS - Adult respiratory distress syndrome'),
    ('Local infections'),
    ('Post TURP'),
    ('Adenomyosis'),
    ('Chikungunya'),
    ('Retroperitoneal mass'),
    ('PUO (Pyrexia of Unknown Origin)'),
    ('Opthal issues'),
    ('Adenocarcinoma'),
    ('Left sided hydronephrosis'),
    ('Functional vs ischemia'),
    ('Barrett esophagus'),
    ('Pain in extensor origin'),
    ('Left proximal uretric calculus'),
    ('Effort intolerance'),
    ('Hydrocele'),
    ('1 mth ammenorhea'),
    ('Intracerebral hemorrhage'),
    ('Right lower limb elephantiasis'),
    ('ALI - Acute lung injury'),
    ('BPH - Benign prostatic hypertrophy'),
    ('Patient wants to Cnt old anti platelet'),
    ('Mental retardation'),
    ('Left sided effusion'),
    ('Phymosis'),
    ('Att was started in dout of kochs by other dr'),
    ('Want to cnt rx for bodyache wth other dr'),
    ('Typhoid fever'),
    ('Cervical spondylosis'),
    ('Acute on chronic pancreastitis'),
    ('Post-hysterectomy menopause'),
    ('Vasculitic infarct'),
    ('CA - Cancer of Buccal Mucosa'),
    ('Cellulitis of left lower limb'),
    ('Anterior uveitis'),
    ('ADPKD - Autosomal dominant polycystic kidney disease'),
    ('Bilateral lower limb varicous vein'),
    ('H/o bleeding per rectum when constipated'),
    ('Post craniotomy status'),
    ('Abdominal kochs vs ibd'),
    ('Dengue'),
    ('Aortic regurgitation'),
    ('Chronic Pancreatitis'),
    ('Post prosthetic valve replacement'),
    ('Parotitis'),
    ('Constrictive pericarditis'),
    ('Bppv'),
    ('Left eye movement restriction'),
    ('Ihd vs gastritis'),
    ('Vegetation over valve'),
    ('Hepatorenal syndrome'),
    ('4 mth ammenorhea'),
    ('Would like to r/o ihd'),
    ('Left shoulder pain and stiffness under evaluation'),
    ('Restricted movement of mitral valve'),
    ('Dextrocardia'),
    ('Right hydronephrosis'),
    ('Want to r/o ihd'),
    ('Hypersplenism'),
    ('HOCM - Hypertrophic obstructive cardiomyopathy'),
    ('Hepatitis under evaluation'),
    ('Pangastritis'),
    ('Hyperbilirubinaemia'),
    ('Type 2 Diabetes Mellitus'),
    ('Left sided pyelonephritis'),
    ('Blindness'),
    ('Conversion Disorder'),
    ('35 week ammenorhea'),
    ('Anaemia'),
    ('Loos of consiousness under evaluation'),
    ('Recurrent cva'),
    ('Left sided staghorn calculus'),
    ('PCOS - Polycystic ovarian syndrome'),
    ('Writers'' cramp'),
    ('Altered sensation under evaluation'),
    ('Pulmonary aneurysm'),
    ('Left upper odema'),
    ('Severe obesity'),
    ('Right lower back radiculopathy'),
    ('Lateral wall ischemia on ecg')
) AS t(val)
WHERE NOT EXISTS (
  SELECT 1 
  FROM public.aka_master_dropdown_catalog 
  WHERE category_id = 8 AND LOWER(value) = LOWER(t.val)
);
