-- SQL script to update lab investigations/tests catalog in public.aka_master_dropdown_catalog
-- Category 30 represents Lab names / Test suggestions.
-- This script deletes all existing test entries and inserts the new list of 400 tests.

-- 1. Delete existing tests (Category 30)
DELETE FROM public.aka_master_dropdown_catalog WHERE category_id = 30;

-- 2. Insert the new 400 tests
INSERT INTO public.aka_master_dropdown_catalog (category_id, value, usage_count)
VALUES
  (30, 'Serum Creatinine', 1),
  (30, 'CBC - Complete Blood Count', 1),
  (30, 'Vitamin D3', 1),
  (30, 'Thyroid-Stimulating Hormone (TSH) Test', 1),
  (30, 'FBS- Fasting Blood Sugar', 1),
  (30, 'PPBS-Postprandial Blood Sugar Test', 1),
  (30, 'HbA1c Test', 1),
  (30, 'Tsh metropolis/ srl', 1),
  (30, 'Xray Chest PA view', 1),
  (30, 'Urine Routine Microscopic (R/M)', 1),
  (30, 'ECG', 1),
  (30, 'Usg a+p wth full and empty bladder', 1),
  (30, 'ESR', 1),
  (30, 'Electrolytes', 1),
  (30, 'CRP', 1),
  (30, 'Stool routine and microscopy', 1),
  (30, 'T3,t4,tsh metro', 1),
  (30, '2D Echo test', 1),
  (30, 'Mp ang', 1),
  (30, 'Serum Ferritin', 1),
  (30, 'Hrct thorax p+ c', 1),
  (30, 'Typhidot IgM', 1),
  (30, 'Serum Iron', 1),
  (30, 'Cag', 1),
  (30, 'Sleep study ,level 3 with titration', 1),
  (30, 'Hb electrophoresis', 1),
  (30, 'Ct a+p with contrast', 1),
  (30, 'Usg a+p', 1),
  (30, 'LDH', 1),
  (30, 'Liver Function Test LFT', 1),
  (30, 'Mri brain p+c', 1),
  (30, 'Mri brain + angio', 1),
  (30, 'Local usg', 1),
  (30, 'HHH', 1),
  (30, 'Lipid Profile Test', 1),
  (30, '24 hr urine for albumin', 1),
  (30, 'Ogd scopy with h pylori testing', 1),
  (30, 'Mri whole spine screening', 1),
  (30, 'CT Coronary Angiography', 1),
  (30, 'BMD- Bone mineral density', 1),
  (30, 'T3 t 4 tsh lupin/srl/metro', 1),
  (30, 'Urine culture and sensitivity wth mic and break point mic', 1),
  (30, 'Sputum for AFB', 1),
  (30, 'Cortisol @ 8 am and 4 pm', 1),
  (30, 'Local usg thyroid', 1),
  (30, 'Xray bilateral knee ap lateral', 1),
  (30, 'Mri LS spine', 1),
  (30, 'Anti tpo antibody', 1),
  (30, 'Stress Test', 1),
  (30, 'Serum uric acid', 1),
  (30, 'Ana by immuno fluroscence technique', 1),
  (30, 'Mri brain with cervical spine', 1),
  (30, 'IgE - Immunoglobulin E', 1),
  (30, 'PTH - Parathyroid Hormone', 1),
  (30, 'Pt inr', 1),
  (30, 'Sputum for gene expert (goverment sponsere)', 1),
  (30, 'Procalcitonin', 1),
  (30, '3 days holter monitoring', 1),
  (30, 'NT-PRO BNP', 1),
  (30, 'Mri whole spine screening with detail study of pathology', 1),
  (30, 'Glucose tolarance test pregnancy protocol', 1),
  (30, 'Serum Prolactin', 1),
  (30, 'ANTI CCP', 1),
  (30, 'Sr ionized calcium level', 1),
  (30, 'Uric Acid', 1),
  (30, 'Trop i', 1),
  (30, 'Spot urine creat albumin ratio', 1),
  (30, 'Dengue ns1;igm,igg', 1),
  (30, 'Ct kub p+c', 1),
  (30, 'Sputum for gene expert', 1),
  (30, 'MRI Cervical Spine', 1),
  (30, 'Stool for cal protactin', 1),
  (30, 'Sleep study level 2 with titration', 1),
  (30, 'Serum Amylase', 1),
  (30, 'Serum Lipase', 1),
  (30, 'Usg a+p adviced to evaluate thrombocytopenia, w/f liver ecotexture,portal vein size', 1),
  (30, 'EEG Electroencephalogram', 1),
  (30, 'SGOT/SGPT', 1),
  (30, 'Serum albumin', 1),
  (30, 'Fibroscan', 1),
  (30, 'RBS (Random Blood Sugar)', 1),
  (30, 'Colonoscopy sos biopsy', 1),
  (30, 'Usg a+ p kindly r/ o abdominal kochs', 1),
  (30, 'Usg guided fnac for gene expert and cytopathology', 1),
  (30, 'Serum Magnesium level', 1),
  (30, 'Body fat propotion', 1),
  (30, 'S. Testosterone', 1),
  (30, 'Ambulatory Blood Pressure Monitoring', 1),
  (30, 'Xray bilateral knee ap lateral standing', 1),
  (30, 'Bt,ct', 1),
  (30, 'Ct kub', 1),
  (30, 'Iron Studies', 1),
  (30, 'Ana blot test', 1),
  (30, 'FT3,FT4,TSH', 1),
  (30, 'Pleural fluid analysis for routine microscopy,ada,gene expert ,culture sensitivity,cytology', 1),
  (30, 'Absolute Eosinophil Count AEC', 1),
  (30, 'Reticulocyte count', 1),
  (30, 'Bilateral venous doppler', 1),
  (30, 'Bronchoscopy with bal analysis', 1),
  (30, 'Xray chest with shield abdomen pt pregnant', 1),
  (30, 'Serum Phosphorus', 1),
  (30, 'PET- CT Whole Body', 1),
  (30, 'Colonoscopy', 1),
  (30, 'HAV Igm Ab', 1),
  (30, 'Usg guided pleural fluid tapping', 1),
  (30, '75-gram Oral Glucose Tolerance Test (OGTT)', 1),
  (30, 'HEV Igm Ab', 1),
  (30, 'Microfilaria antigen Test', 1),
  (30, 'HBV viral load quantitative', 1),
  (30, 'Dsa', 1),
  (30, 'Colonoscopy with biosy', 1),
  (30, 'Serum c3 c4 complement level', 1),
  (30, 'Mri bilateral hip joint', 1),
  (30, 'Arterial Blood Gas (ABG) Test', 1),
  (30, 'Ct guided biopsy for gene expert. And histopathology', 1),
  (30, 'Mri left shoulder', 1),
  (30, 'HLA B27', 1),
  (30, 'Local usg scrotum', 1),
  (30, 'Ct brain plain', 1),
  (30, 'MRI Thoracolumbar Spine', 1),
  (30, 'EMG/NCV Tests', 1),
  (30, 'B12 level', 1),
  (30, 'Peripheral smear for wbc ,rbc,platlet morphology sehgal lab', 1),
  (30, 'Right lower limb venous doppler', 1),
  (30, 'Fnac for gene expert and cytopathology', 1),
  (30, 'Renal arterial doppler', 1),
  (30, 'Sputum for gram stain', 1),
  (30, 'Serum erythropoeitin level', 1),
  (30, 'Local usg thyroid look for parathyroid', 1),
  (30, 'Left lower limb venous doppler', 1),
  (30, 'IPF - Immature Platelet Fraction', 1),
  (30, 'MRI Thoracic spine', 1),
  (30, 'Mri right shoulder', 1),
  (30, 'Igg for entamoeba histocolitica', 1),
  (30, 'Ct neck p+ c', 1),
  (30, 'Sputum Culture & Sensitivity', 1),
  (30, 'Serum ace level', 1),
  (30, 'JAK2 mutation', 1),
  (30, 'Right upper limb ncv emg', 1),
  (30, 'Cd4 count', 1),
  (30, 'ABPA panel - Allergic bronchopulmonary aspergillosis', 1),
  (30, 'G6PD', 1),
  (30, 'Hiv viral load', 1),
  (30, 'Physiotherapy', 1),
  (30, 'MRCP - Magnetic Resonance Cholangio-Pancreatography', 1),
  (30, 'Blood Culture & Sensitivity', 1),
  (30, 'Hrct thorax plain', 1),
  (30, 'CT Pulmonary Angiogram', 1),
  (30, 'Local usg left breast', 1),
  (30, 'P - ANCA', 1),
  (30, 'Xray whole spine ap lateral', 1),
  (30, 'Mri ls spine plus pbh', 1),
  (30, 'Tsh lupin/ metro', 1),
  (30, 'Serum Bilirubin', 1),
  (30, 'Xray ls spine ap lateral', 1),
  (30, 'Prostate-Specific Antigen (PSA)', 1),
  (30, 'Ogd scopy', 1),
  (30, 'Bcr abl assay', 1),
  (30, 'X Ray Chest', 1),
  (30, 'Xray Knee AP/Lateral Right side', 1),
  (30, 'Xray foot ap/lat right side', 1),
  (30, 'Mri ls spine with stir image', 1),
  (30, 'Skin prick test', 1),
  (30, 'C - ANCA', 1),
  (30, 'Manual platlet count', 1),
  (30, 'Emg/ncv bilateral lower limb', 1),
  (30, 'PFT with bronchodilator', 1),
  (30, 'Cbc advance test', 1),
  (30, 'CT Scan PNS', 1),
  (30, 'Usg guided ascitic fluid tapping', 1),
  (30, 'Serum Protein Electrophoresis', 1),
  (30, 'D Dimer', 1),
  (30, 'Ogd scopy sos biopsy', 1),
  (30, 'MRI knee (Left)', 1),
  (30, 'Transesophageal Echocardiogram (TEE)', 1),
  (30, 'MRI knee (Right)', 1),
  (30, 'Emg ncv all 4 limb', 1),
  (30, '2 decho', 1),
  (30, 'Igm igg microfilaria', 1),
  (30, 'Xray abdomen erect', 1),
  (30, 'DCT - Direct Coombs Test', 1),
  (30, 'Csf study', 1),
  (30, 'Ascit fluid analysis-routine microscopy,ada,gene expert,cytology,culture sensitivit,gram stain', 1),
  (30, 'HBeAg', 1),
  (30, 'Usg a+p full bladder', 1),
  (30, 'Hrct bilateral temporal bone', 1),
  (30, 'Arterial doppler bilateral lower limb', 1),
  (30, 'ECG Electrocardiogram', 1),
  (30, 'INR test', 1),
  (30, 'Usg w/f fatty liver', 1),
  (30, 'Vanillylmandelic Acid (VMA) Urine', 1),
  (30, 'Right upper limb arterial doppler', 1),
  (30, 'MRI Brain', 1),
  (30, 'Xray left foot ap lateral', 1),
  (30, 'ICT - Indirect Coombs Test', 1),
  (30, 'AChR-Acetylcholine Receptor Antibody', 1),
  (30, 'UROFLOWMETRY', 1),
  (30, 'Usg a+o empty stomach', 1),
  (30, 'Usg guided fnac for gene expert and histopath', 1),
  (30, 'Usg a+p empty stomach', 1),
  (30, 'Insulin fasting level', 1),
  (30, 'HBeAB', 1),
  (30, 'Pleural Fluid Analysis', 1),
  (30, 'Pus to be send for gene expert', 1),
  (30, 'S. Typhi IgM', 1),
  (30, 'C peptide level', 1),
  (30, 'Quantiferon-TB Gold', 1),
  (30, 'Mri b/l hip joint', 1),
  (30, 'Cerebral dsa', 1),
  (30, '2d echo with ivc diameter', 1),
  (30, 'Hla b27 metropolis', 1),
  (30, 'Head Up Tilt Table Test', 1),
  (30, 'Hcv viral load', 1),
  (30, 'ERCP - Endoscopic Retrograde Cholangio-Pancreatography', 1),
  (30, 'APTT - Activated Partial Thromboplastin Time', 1),
  (30, 'Hbsag', 1),
  (30, 'Ct kub plain sos contrast', 1),
  (30, 'Mri whole spine screening sos detail study of pathology', 1),
  (30, 'MRI Brain Epilepsy Protocol', 1),
  (30, 'Right upper limb ncv test', 1),
  (30, 'Blood grouping', 1),
  (30, 'Left lower limb arterial doppler', 1),
  (30, 'Hrct thorax plain sos contrast', 1),
  (30, 'Ct aortogram', 1),
  (30, 'Serum insulin level', 1),
  (30, 'Cpkmb', 1),
  (30, 'Usg guided fnac for cytopathology', 1),
  (30, 'Xray pbh', 1),
  (30, 'Local usg breast', 1),
  (30, 'Sputum for lpa 1 and lpa 2', 1),
  (30, 'Ascitic Fluid Analysis', 1),
  (30, 'Rubella antibody titres', 1),
  (30, 'Loca usg comparitive study', 1),
  (30, 'Sleep study', 1),
  (30, 'Sputum for mgit culture', 1),
  (30, 'Mri right lower limb', 1),
  (30, 'Emg ncv left upper limb', 1),
  (30, 'Ogdscopy with variceal binding', 1),
  (30, 'Repeat urine culture and sensitivity', 1),
  (30, 'Usg axila and breast', 1),
  (30, 'Local left axila usg', 1),
  (30, 'Ct angio right lower limb', 1),
  (30, 'USG KUB(kidneys, ureters, and bladder)', 1),
  (30, 'Ct guided Liver biopsy', 1),
  (30, 'Varicella ig m igg', 1),
  (30, 'Mri rain p+c with dedicated pitutary study', 1),
  (30, 'Ct brain p+cApla profile', 1),
  (30, 'Mri brain p+c with left orbit study', 1),
  (30, 'Fluid Aspiration (Usg guided)', 1),
  (30, 'Ct brain plain f/b mri brain angio after stabilization', 1),
  (30, 'Mri bilateral orbit', 1),
  (30, 'Xray left shoulder ap/lateral', 1),
  (30, 'Usg to r/o rpoc or infection', 1),
  (30, 'Check cag', 1),
  (30, 'Emg ncv bilateral upper limb', 1),
  (30, 'Ogd scopy with sos variceal banding', 1),
  (30, 'Antimitochondrial Antibody Test - AMA', 1),
  (30, 'Ca 125', 1),
  (30, 'Pus culture and sensitivity with mic and break point mic', 1),
  (30, 'Mri brain p+c epilepsy protocol', 1),
  (30, 'Mumps antibody titer', 1),
  (30, 'Ct brain angio', 1),
  (30, 'Anti-LKM 1 Liver Kidney Microscopic', 1),
  (30, 'TPHA-Treponema pallidum particle agglutination assay', 1),
  (30, 'Xray Ankle AP/ Lateral Right side', 1),
  (30, 'Ct esophagus cut and abd w', 1),
  (30, 'Cbc sehgal', 1),
  (30, 'Mri brain p+c with. Focus right orbit study', 1),
  (30, 'Usg with fibro scan', 1),
  (30, 'Cervical Lymph Biopsy', 1),
  (30, 'Hba1c lupin/metro/srl', 1),
  (30, 'Beta hCG', 1),
  (30, 'Hepatitis a antibody titers', 1),
  (30, 'Not complaint yo dose of insulin', 1),
  (30, 'Usg a+p r /o soft tissue injury', 1),
  (30, 'T3,t4,tsh on follow up', 1),
  (30, 'Anti-Smooth Muscle Antibody - ASMA', 1),
  (30, 'Bilateral venous doppler kindly comment on varicosity also wth deep vein status', 1),
  (30, 'Ct angio left lower limb', 1),
  (30, 'Mri brain p+c wth focus pitutary study', 1),
  (30, 'Pus for fungal culture and sensitivity', 1),
  (30, 'Sputum for mgit 15 drug panel', 1),
  (30, 'Urologist reference', 1),
  (30, 'Mri right thigh sos', 1),
  (30, 'Plan for cag', 1),
  (30, 'Ogd scopy withh pylori testing and manometery', 1),
  (30, 'Mri parotid', 1),
  (30, 'Usg a+p r/o liver cirhosis', 1),
  (30, 'Thrombophilia profile', 1),
  (30, 'Mri right ankle', 1),
  (30, 'Lpa1 and lpa2', 1),
  (30, 'Mri left upper limb and shoulder', 1),
  (30, 'Hrct thorax', 1),
  (30, 'Bilateral lower limb venous doppler', 1),
  (30, 'PET Scan', 1),
  (30, 'Cpk mb total', 1),
  (30, 'PT/INR (Prothrombin Time and International Normalized Ratio)', 1),
  (30, 'Mri right hand', 1),
  (30, 'Biopsy of lymph node', 1),
  (30, 'Entameba igm iggg', 1),
  (30, 'Urodynamic study at fortis mulund', 1),
  (30, 'CT Paranasal Sinuses', 1),
  (30, 'Right lower limb local usg', 1),
  (30, 'Mri left foot', 1),
  (30, 'Csf fluid analysis', 1),
  (30, 'Nipple discharge for r/m and culture', 1),
  (30, 'Measles antibody titres', 1),
  (30, 'Mri ls spine sos', 1),
  (30, 'Ct neck with oseophageal cut', 1),
  (30, 'Tissue for mgit culture and sensitivity', 1),
  (30, 'Ncv bilateral lower limb', 1),
  (30, 'Mri right foot', 1),
  (30, 'Free Testosterone', 1),
  (30, 'Cardiac MRI', 1),
  (30, 'Mri brain with whole spine screening', 1),
  (30, 'Pus for lpa1 And lpa2', 1),
  (30, 'Biopsy for gene expert,histopsthology,mgit culture sensitivity,aerobic and anerobic culture of biopsised tissue', 1),
  (30, 'Sperm Analysis', 1),
  (30, 'Xray right hand ap laterL', 1),
  (30, 'Ct brain and cervical spine', 1),
  (30, 'Bone marrow biopsy', 1),
  (30, 'Eus guided biopsy', 1),
  (30, 'Usg bilateral breast', 1),
  (30, 'Xray left knee ap/lateral', 1),
  (30, 'Homocysteine', 1),
  (30, 'Peripheral smear for rbc,wbc,platlet morphology', 1),
  (30, 'Biopsy for histopath', 1),
  (30, 'Sos udg guided fnac of thyroid', 1),
  (30, 'Semen Analysis', 1),
  (30, 'B/l lower limb doppler venous', 1),
  (30, 'HCV IgM', 1),
  (30, 'Creat on follow up', 1),
  (30, 'Tissue for histopath gene expert', 1),
  (30, 'RFT', 1),
  (30, 'Fundoscopy to r/o diabetic retinopathy', 1),
  (30, 'Subclavian cag', 1),
  (30, 'Western blot', 1),
  (30, 'Mri brain angio p+c f/b dialysis', 1),
  (30, 'Mri oral cavity', 1),
  (30, 'Usg a+p look for fatty liver', 1),
  (30, 'Local usg right breast', 1),
  (30, 'Follow up echo', 1),
  (30, 'FSH (Follicle-Stimulating Hormone)', 1),
  (30, 'Local usg for hernia', 1),
  (30, 'Pus for bacterial culture and sensitivity', 1),
  (30, 'Xray right elbow ap/lateral', 1),
  (30, 'Usg a+p w/f renal cal,cytitis,hernia', 1),
  (30, 'Local usg neck', 1),
  (30, 'Sputum for culture and sensitivity aerobic and anerobic', 1),
  (30, 'Usg w/f cld ,liver ecotexture', 1),
  (30, 'Hba1c on follow up', 1),
  (30, 'Pus for bacterial culture and sensitivity aerobican aerobic with mic and break point mic', 1),
  (30, 'LH - Leutinizing Hormone', 1),
  (30, 'Xray Dorsal Spine AP/LAT', 1),
  (30, 'Local usg left upper limb and breast', 1),
  (30, 'Bmd scan', 1),
  (30, 'Serum insulin level fasting and post meal', 1),
  (30, 'Xray Ankle AP/ Lateral Left side', 1),
  (30, 'C-Peptide Fasting', 1),
  (30, 'Pus for mgit culture and sensitivity', 1),
  (30, 'Er pr her 2 neu and ki 67', 1),
  (30, 'Localusg scrotum', 1),
  (30, 'Tsh metro/srl/ lupin on follow up', 1),
  (30, 'Serum Phosphate level', 1),
  (30, 'EBUS-TBNA( Endobronchial ultrasound-guided transbronchial needle aspiration )', 1),
  (30, 'Mri whole spine screening with sos detail study of pathology', 1),
  (30, 'Stool for fat content and quantification', 1),
  (30, 'Peripheral smear for wbc morphology', 1),
  (30, 'Mri right elbow', 1),
  (30, 'Ct brain plain sos contrast', 1),
  (30, 'Serum Electrolyte', 1),
  (30, 'Total Testosterone', 1),
  (30, '3d ct face', 1),
  (30, 'Usga+p kindly comment on liver ecotexture,portil vein,splenic size', 1),
  (30, 'Perimetry Test', 1),
  (30, 'Hrct thorac p+c comparitive study', 1),
  (30, 'Mri right leg', 1),
  (30, 'HIV rapid screening test', 1),
  (30, 'Ct a+p p+c comparitive study', 1),
  (30, 'Hepatitis B antibody titres', 1),
  (30, 'Usg a+p watch for fatty liver', 1),
  (30, 'Repeat endoscopy guided histopath', 1),
  (30, 'Ct guided biopsy for gene expert and histopath and mgit culture wth sensitivity', 1),
  (30, 'Cect oral cavity and neck puff cheek', 1),
  (30, 'Ct brain plain with cervical spine', 1),
  (30, 'Streotactic biopsy of brain', 1),
  (30, 'Bilateral lower limb venous doppler w/f varocity', 1),
  (30, 'Vit b12', 1),
  (30, 'Xray for age determination', 1),
  (30, 'Ct a+p with oral contrast only', 1),
  (30, 'Urine culture and sensitivity wth mic', 1),
  (30, 'Right lower limb arterial doppler', 1),
  (30, 'Upt', 1),
  (30, 'Stone analysis', 1),
  (30, 'Hbe ang', 1),
  (30, 'Inr patient on warf', 1),
  (30, 'Mri brain angio p+c', 1),
  (30, 'Dengue igm igg', 1),
  (30, 'Renal biopsy', 1),
  (30, 'Sr .Cholestrol', 1),
  (30, 'Ca 19.9', 1),
  (30, 'Mri left elbow', 1)
ON CONFLICT DO NOTHING;
