-- Symptoms Catalog Seed SQL
DELETE FROM public.aka_master_dropdown_catalog WHERE category_id = 1;

INSERT INTO public.aka_master_dropdown_catalog (category_id, value, usage_count) VALUES
  (1, '1 Episode Of Loss Of Consciousness', 1),
  (1, '1 Episode Of Syncope', 1),
  (1, 'AOE', 1),
  (1, 'Abdomen Discomfort', 1),
  (1, 'Abdominal Bloating', 1),
  (1, 'Abdominal Discomfort', 1),
  (1, 'Abdominal Distension', 1),
  (1, 'Abdominal Fullness', 1),
  (1, 'Abdominal Pain', 1),
  (1, 'Action Tremor', 1),
  (1, 'Anorexia', 1),
  (1, 'Anorexic', 1),
  (1, 'Anuria', 1),
  (1, 'Backache', 1),
  (1, 'Backpain', 1),
  (1, 'Bechaini', 1),
  (1, 'Bilateral Chest Pain', 1),
  (1, 'Bilateral Heel Pain', 1),
  (1, 'Bilateral Jaw Area Pain', 1),
  (1, 'Bilateral Knee Pain', 1),
  (1, 'Bilateral Lower Limb Pain', 1),
  (1, 'Bilateral Lower Limb Swelling', 1),
  (1, 'Bilateral Lower Limb Weakness', 1),
  (1, 'Bilateral Pedal Oedema', 1),
  (1, 'Bilateral Shoulder Pain', 1),
  (1, 'Bilateral Upper Limb Pain', 1),
  (1, 'Bilateral Upper Limb Small Joint Stiffness', 1),
  (1, 'Bleeding From Mouth', 1),
  (1, 'Bleeding Per Rectum', 1),
  (1, 'Bleeding While Stool', 1),
  (1, 'Blood In Sputum', 1),
  (1, 'Blood In Stool', 1),
  (1, 'Blood In Urine', 1),
  (1, 'Blood In Vomitus', 1),
  (1, 'Blood Stained Sputum', 1),
  (1, 'Bluish Discolouration', 1),
  (1, 'Blurring Of Vision', 1),
  (1, 'Bodyache', 1),
  (1, 'Breathlessness', 1),
  (1, 'Buring Around Perinium', 1),
  (1, 'Burning Chest', 1),
  (1, 'Burning Micturition', 1),
  (1, 'Burning Of Chest', 1),
  (1, 'Burning Sensation Of Abdomen', 1),
  (1, 'Burning Sensation Over Back', 1),
  (1, 'Burping', 1),
  (1, 'Change Of Voice', 1),
  (1, 'Chest Discomfort', 1),
  (1, 'Chest Pain', 1),
  (1, 'Chest Ticking Pain', 1);

INSERT INTO public.aka_master_dropdown_catalog (category_id, value, usage_count) VALUES
  (1, 'Cold', 1),
  (1, 'Constipation', 1),
  (1, 'Convulsion', 1),
  (1, 'Cough', 1),
  (1, 'Cough With Expectoration', 1),
  (1, 'Cramp', 1),
  (1, 'Cramps In Leg', 1),
  (1, 'DIB - Difficulty In Breathing', 1),
  (1, 'DOE', 1),
  (1, 'DOE AOE', 1),
  (1, 'Decreased Appetite', 1),
  (1, 'Deviation Of Mouth To Left', 1),
  (1, 'Diaphoresis', 1),
  (1, 'Diarrhea', 1),
  (1, 'Different Sensation Of Head', 1),
  (1, 'Difficulty In Passing Urine', 1),
  (1, 'Difficulty In Speech', 1),
  (1, 'Difficulty Passing Urine', 1),
  (1, 'Difficulty Swallowing', 1),
  (1, 'Difficulty Walking', 1),
  (1, 'Difficulty With Micturition', 1),
  (1, 'Diplopia', 1),
  (1, 'Discoluration Of Urine', 1),
  (1, 'Disturbed Sleep Pattern', 1),
  (1, 'Dizziness', 1),
  (1, 'Dryness Of Eyes', 1),
  (1, 'Dryness Of Mouth', 1),
  (1, 'Dysphagia', 1),
  (1, 'Early Morning Stiffness', 1),
  (1, 'Easy Fatigability', 1),
  (1, 'Epigastric Burning', 1),
  (1, 'Epigastric Discomfort', 1),
  (1, 'Episode Of Anxiety ,palpitation,sweating', 1),
  (1, 'Episode Of Involuntary Sudden Onset Tonic Clonic Movement', 1),
  (1, 'Episode Of Panic Intermittent', 1),
  (1, 'Episodes Of Unconciousness', 1),
  (1, 'Episodic Ghabrahat', 1),
  (1, 'Epistaxis', 1),
  (1, 'Eruptions On Face', 1),
  (1, 'Excessive Sleeping', 1),
  (1, 'Excessive Sweating', 1),
  (1, 'Facial Puffiness', 1),
  (1, 'Fatigue', 1),
  (1, 'Feels Feverish', 1),
  (1, 'Feels Like Crying', 1),
  (1, 'Fever', 1),
  (1, 'Fever/chills', 1),
  (1, 'Feverish', 1),
  (1, 'Flatulence', 1),
  (1, 'Freezing Of Gait', 1);

INSERT INTO public.aka_master_dropdown_catalog (category_id, value, usage_count) VALUES
  (1, 'Frequent Oral Ulcer', 1),
  (1, 'General Weakness', 1),
  (1, 'Generalised Oedema', 1),
  (1, 'Generalised Swelling', 1),
  (1, 'Generalized Swelling', 1),
  (1, 'Ghabrahat', 1),
  (1, 'Giddiness', 1),
  (1, 'Glair In Front Of Eyes', 1),
  (1, 'Growth Over Right Toe', 1),
  (1, 'Had 2 Episodes Of Loss Of Consciousness', 1),
  (1, 'Hairfall', 1),
  (1, 'Head Burning', 1),
  (1, 'Head Heaviness', 1),
  (1, 'Headache', 1),
  (1, 'Heaviness In Chest', 1),
  (1, 'Heaviness Of Forehead', 1),
  (1, 'Heel Pain', 1),
  (1, 'Hematemesis', 1),
  (1, 'Hemoptysis', 1),
  (1, 'Imbalance', 1),
  (1, 'Increased Frequency Of Urine', 1),
  (1, 'Increased Pv Discharged', 1),
  (1, 'Increased Sleep', 1),
  (1, 'Indigestion', 1),
  (1, 'Insomnia', 1),
  (1, 'Intermittent Episode Of Sweating', 1),
  (1, 'Involuntary Movement', 1),
  (1, 'Involuntary Tremors Of Left Upper Limb', 1),
  (1, 'Involuntary Weight Gain', 1),
  (1, 'Involuntary Weight Loss', 1),
  (1, 'Irregular Menses', 1),
  (1, 'Irrelevant Behavior', 1),
  (1, 'Irrelevant Talks', 1),
  (1, 'Irritability', 1),
  (1, 'Irritation In The Throat', 1),
  (1, 'Itching All Over Body', 1),
  (1, 'Itching Bilateral Lower Limb', 1),
  (1, 'Itching Local Area', 1),
  (1, 'Itching Over Back', 1),
  (1, 'Itching Over Fore Head', 1),
  (1, 'Itching Over Hand', 1),
  (1, 'Itching Over Neck', 1),
  (1, 'Itching Per Vaginal', 1),
  (1, 'Jery Movement Of Hand Left More Than Right', 1),
  (1, 'Joint Stiffness', 1),
  (1, 'Lack Of Appetite', 1),
  (1, 'Laziness', 1),
  (1, 'Left Back Pain', 1),
  (1, 'Left Breast Tenderness', 1),
  (1, 'Left Flank Pain', 1);

INSERT INTO public.aka_master_dropdown_catalog (category_id, value, usage_count) VALUES
  (1, 'Left Foot Pain And Tenderness', 1),
  (1, 'Left Foot Swelling', 1),
  (1, 'Left Hand Pain', 1),
  (1, 'Left Heel Pain', 1),
  (1, 'Left Hemi Pain', 1),
  (1, 'Left Hypochondrial Pain', 1),
  (1, 'Left LL (Lower Limb) Weakness', 1),
  (1, 'Left Lower Back Pain', 1),
  (1, 'Left Lower Face Numbness', 1),
  (1, 'Left Lower Limb Swelling', 1),
  (1, 'Left Lower Limb Tingling Numbness', 1),
  (1, 'Left Side Body Tingling', 1),
  (1, 'Left Sided Body Ache', 1),
  (1, 'Left Sided Chest Discomfort', 1),
  (1, 'Left Sided Chest Pain', 1),
  (1, 'Left Sided Flank Pain', 1),
  (1, 'Left Sided Pain', 1),
  (1, 'Left Testicular Pain', 1),
  (1, 'Left Thoracic Pain', 1),
  (1, 'Left Upper Chest Lump', 1),
  (1, 'Left Upper Limb And Lower Limb Tingling Numbness', 1),
  (1, 'Left Upper Limb And Lower Limb Weakness', 1),
  (1, 'Left Upper Limb Claudication', 1),
  (1, 'Left Upper Limb Lower-limb Pain', 1),
  (1, 'Left Upper Limb Pain', 1),
  (1, 'Left Upper Limb Pain Radiating In Nature', 1),
  (1, 'Left Upper Limb Swelling And Pain', 1),
  (1, 'Left Upper Limb Weakness', 1),
  (1, 'Lethargic', 1),
  (1, 'Local Echymosis', 1),
  (1, 'Local Itching', 1),
  (1, 'Local Itching Over Glans', 1),
  (1, 'Local Lump Over Abdomen', 1),
  (1, 'Local Lump Over Neck', 1),
  (1, 'Local Pain', 1),
  (1, 'Local Pain And Tenderness', 1),
  (1, 'Local Rash With Itching', 1),
  (1, 'Local Redness', 1),
  (1, 'Local Swelling And Pain Left Axila', 1),
  (1, 'Local Swelling And Pain Left Testes', 1),
  (1, 'Local Swelling Around Bed Nail', 1),
  (1, 'Local Swelling Over Back', 1),
  (1, 'Local Swelling Over Chest', 1),
  (1, 'Local Swelling Over Epigastric Area', 1),
  (1, 'Local Swelling Over Left Foot', 1),
  (1, 'Local Swelling Over Lips', 1),
  (1, 'Local Swelling Over Neck', 1),
  (1, 'Local Swelling Over Penis', 1),
  (1, 'Local Swelling Over Scalp', 1),
  (1, 'Local Swelling Over Thigh Right Thigh', 1);

INSERT INTO public.aka_master_dropdown_catalog (category_id, value, usage_count) VALUES
  (1, 'Local Swelling Over Tongue', 1),
  (1, 'Local Swelling Over Waist', 1),
  (1, 'Loose Motion', 1),
  (1, 'Loose Stool', 1),
  (1, 'Loose Stools', 1),
  (1, 'Loss Of Appetite', 1),
  (1, 'Loss Of Balance', 1),
  (1, 'Loss Of Consciousness', 1),
  (1, 'Loss Of Control Over Body', 1),
  (1, 'Loss Of Memory', 1),
  (1, 'Low Back Pain', 1),
  (1, 'Low Backache', 1),
  (1, 'Lower Abdominal Pain', 1),
  (1, 'Lump In Breast B/L', 1),
  (1, 'Lump In Breast Left Side', 1),
  (1, 'Lump In Right Breast', 1),
  (1, 'Maas Over Right Shin', 1),
  (1, 'Menorrhagia', 1),
  (1, 'Mucus In Stool', 1),
  (1, 'Multi Episodes Of Loss Of Consciousness', 1),
  (1, 'Multiple Joint Pain', 1),
  (1, 'Multiple Small Joint Pain And Swelling', 1),
  (1, 'Nasal Bleeding', 1),
  (1, 'Nasal Stuffiness', 1),
  (1, 'Nausea', 1),
  (1, 'Nausea And Vomiting', 1),
  (1, 'Neck Pain', 1),
  (1, 'Oral Boils', 1),
  (1, 'Oral Ulceration', 1),
  (1, 'Pain And Discomfort Non Specefic Site', 1),
  (1, 'Pain In Abdomen', 1),
  (1, 'Pain In Epigastrium', 1),
  (1, 'Pain In Left Hip Area', 1),
  (1, 'Pain In Left Leg', 1),
  (1, 'Pain In Left Lower Limb', 1),
  (1, 'Pain In Left Lower Limb Radiating In Nature', 1),
  (1, 'Pain In Left Shoulder', 1),
  (1, 'Pain In Left Shoulder And Stiffness', 1),
  (1, 'Pain In Left Thumb', 1),
  (1, 'Pain In Right Foot', 1),
  (1, 'Pain In Right Hand', 1),
  (1, 'Pain In Right Hip', 1),
  (1, 'Pain In Right Upper Limb', 1),
  (1, 'Pain In Right Wrist', 1),
  (1, 'Pain Left Knee', 1),
  (1, 'Pain Of Jaw', 1),
  (1, 'Pain On Passing Urine', 1),
  (1, 'Pain Over Right Toe', 1),
  (1, 'Pain Per Ano', 1),
  (1, 'Pain Per Rectal', 1);

INSERT INTO public.aka_master_dropdown_catalog (category_id, value, usage_count) VALUES
  (1, 'Pain Right Ear', 1),
  (1, 'Pain Right Maxilary Area', 1),
  (1, 'Pain Right Upper Limb And Lower Limb', 1),
  (1, 'Pain Upper Back On Coughing', 1),
  (1, 'Painful Menses', 1),
  (1, 'Palpitations', 1),
  (1, 'Paresthesia (Numbness/tingling) Of Lower Limb', 1),
  (1, 'Peri Orbital Swelling', 1),
  (1, 'Perianal Pain', 1),
  (1, 'Petechial Rash', 1),
  (1, 'Premature Ejaculation', 1),
  (1, 'Productive Cough', 1),
  (1, 'Rash Over Abd And Back', 1),
  (1, 'Rash Over Body', 1),
  (1, 'Rash Over The Face', 1),
  (1, 'Rash With Itching', 1),
  (1, 'Rectal Prolapse', 1),
  (1, 'Recurrent Boils', 1),
  (1, 'Recurrent Cold', 1),
  (1, 'Recurrent Oral Ulcer', 1),
  (1, 'Redish Discoluration Of Urine', 1),
  (1, 'Retention Of Urine', 1),
  (1, 'Right Ankle Pain', 1),
  (1, 'Right Arm Herpetiform Lesion', 1),
  (1, 'Right Elbow Lump', 1),
  (1, 'Right Flank Pain', 1),
  (1, 'Right Gynacomastia', 1),
  (1, 'Right Hand Tingling Sensation', 1),
  (1, 'Right Heel Pain', 1),
  (1, 'Right Hypochondrial Pain', 1),
  (1, 'Right Jugular Pain And Swelling', 1),
  (1, 'Right Knee Pain', 1),
  (1, 'Right Leg Pain', 1),
  (1, 'Right Lower Back Pain', 1),
  (1, 'Right Lower Chest Pain', 1),
  (1, 'Right Lower Knee Burn', 1),
  (1, 'Right Lower Leg Pain And Redness', 1),
  (1, 'Right Lower Limb Numbeness And Weakness', 1),
  (1, 'Right Lower Limb Pain', 1),
  (1, 'Right Lower Limb Pain And Swelling', 1),
  (1, 'Right Lower Limb Pain Radiating Nature', 1),
  (1, 'Right Lower Limb Swelling', 1),
  (1, 'Right Lower Limb Tingling Numbness', 1),
  (1, 'Right Lower Limb Weakness', 1),
  (1, 'Right Shoulder Pain', 1),
  (1, 'Right Sided Abdominal Pain', 1),
  (1, 'Right Sided Burning Over Chest', 1),
  (1, 'Right Sided Chest Pain', 1),
  (1, 'Right Sided Neck Swelling', 1),
  (1, 'Right Sided Weakness', 1);

INSERT INTO public.aka_master_dropdown_catalog (category_id, value, usage_count) VALUES
  (1, 'Right Testicular Pain', 1),
  (1, 'Right Thumb Pain', 1),
  (1, 'Right Upper And Lower Limbweakness', 1),
  (1, 'Right Upper Limb And Lower Limb Tingling Numbness', 1),
  (1, 'Right Upper Limb Lower Limb Numbness', 1),
  (1, 'Right Upper Limb Swelling', 1),
  (1, 'Right Upper Limb Weakness', 1),
  (1, 'Right Upper Redness And Fever', 1),
  (1, 'Running Nose', 1),
  (1, 'Sensation Over Peri Oral Area', 1),
  (1, 'Sever Pain In Abdomen', 1),
  (1, 'Sneezing', 1),
  (1, 'Sore Throat', 1),
  (1, 'Sprain', 1),
  (1, 'Stairy Look', 1),
  (1, 'Sub Mental Lymphnode Pain', 1),
  (1, 'Sudden Onset Deviation Of Mouth', 1),
  (1, 'Sudden Onset Difficulty In Speech', 1),
  (1, 'Sudden Onset Ghabrahat', 1),
  (1, 'Sudden Onset Jerky Movement Of The Body', 1),
  (1, 'Sudden Onset Loss Of Consciousness', 1),
  (1, 'Sudden Onset Loss Of Vision', 1),
  (1, 'Sudden Onset Spasm Of All 4 Limb', 1),
  (1, 'Sudden Onset Sweating', 1),
  (1, 'Sudden Twisting Of Right Upper Limb', 1),
  (1, 'Suprapubic Pain', 1),
  (1, 'Sweating', 1),
  (1, 'Swelling All Over The Body', 1),
  (1, 'Swelling And Pain Right Ankle', 1),
  (1, 'Swelling Of Left Leg', 1),
  (1, 'Swelling Over Eyes', 1),
  (1, 'Swelling Over Face', 1),
  (1, 'Swelling Over Feet', 1),
  (1, 'Swelling Over Penis', 1),
  (1, 'Swelling Over Right Side Chest', 1),
  (1, 'Swelling Over The Neck', 1),
  (1, 'Swelling Right Hand Pain', 1),
  (1, 'Throat Discomfort', 1),
  (1, 'Throat Pain', 1),
  (1, 'Throat Pain Post Meal,relives After Walking,swelling Redness Over Body Post Exposure To Water', 1),
  (1, 'Tingling And Numbness All 4 Limb', 1),
  (1, 'Tingling And Numbness Of Upper Limb', 1),
  (1, 'Tingling Numbness All Over The Body', 1),
  (1, 'Tingling Numbness Of Bilateral Upper Limb', 1),
  (1, 'Tingling Numbness Of Right Upper Limb', 1),
  (1, 'Tingling Numbness Of Right Upper Limb And Lower Limb', 1),
  (1, 'Tingling Sensation Over Chest', 1),
  (1, 'Toothache', 1),
  (1, 'Twiching Pain In Chest', 1),
  (1, 'Twisting Of Hand', 1);

INSERT INTO public.aka_master_dropdown_catalog (category_id, value, usage_count) VALUES
  (1, 'UI - Urinary Incontinence', 1),
  (1, 'Unexplained Gain', 1),
  (1, 'Unsatisfying Stool', 1),
  (1, 'Upper Backpain', 1),
  (1, 'Urine Incontinence', 1),
  (1, 'Urticaria', 1),
  (1, 'Voice Hoarseness', 1),
  (1, 'Vomiting', 1),
  (1, 'Weight Gain', 1),
  (1, 'Weight Loss', 1),
  (1, 'White Vaginal Discharge', 1);

