-- SQL script to update procedures catalog in public.aka_master_dropdown_catalog
-- Category 60 represents Procedure names.
-- This script deletes all existing procedure entries and inserts the new list.

-- 1. Delete existing procedures (Category 60)
DELETE FROM public.aka_master_dropdown_catalog WHERE category_id = 60;

-- 2. Insert the new procedure suggestions
INSERT INTO public.aka_master_dropdown_catalog (category_id, value, usage_count)
VALUES
  (60, 'Wound Dressing', 1),
  (60, 'Nebulization', 1),
  (60, 'IV Cannulation', 1),
  (60, 'IM Injection', 1),
  (60, 'Catheterization', 1),
  (60, 'Suture Removal', 1),
  (60, 'Ear Syringing', 1),
  (60, 'Ryle''s Tube Insertion', 1),
  (60, 'Ascitic Tapping', 1),
  (60, 'Pleural Tapping', 1),
  (60, 'Abscess Drainage', 1),
  (60, 'Intravenous (IV) Infusion', 1),
  (60, 'Blood Transfusion', 1),
  (60, 'Platelet Transfusion', 1),
  (60, 'FFP Transfusion', 1),
  (60, 'Oxygen Therapy', 1),
  (60, 'Steam Inhalation', 1),
  (60, 'Enema Administration', 1),
  (60, 'Gastric Lavage (Stomach Wash)', 1),
  (60, 'Nasogastric Tube Feeding', 1),
  (60, 'Urinary Catheter Removal', 1),
  (60, 'Central Venous Line Insertion', 1),
  (60, 'Arterial Line Insertion', 1),
  (60, 'Endotracheal Intubation', 1),
  (60, 'Tracheostomy', 1),
  (60, 'Cricothyrotomy', 1),
  (60, 'CPR (Cardiopulmonary Resuscitation)', 1),
  (60, 'Defibrillation (Cardioversion)', 1),
  (60, 'Lumbar Puncture (Spinal Tap)', 1),
  (60, 'Bone Marrow Aspiration', 1),
  (60, 'Bone Marrow Biopsy', 1),
  (60, 'Joint Aspiration (Arthrocentesis)', 1),
  (60, 'Needle Decompression', 1),
  (60, 'Intercostal Drainage (ICD) Insertion', 1),
  (60, 'Chest Tube Removal', 1),
  (60, 'Peritoneal Dialysis', 1),
  (60, 'Hemodialysis', 1),
  (60, 'Continuous Renal Replacement Therapy (CRRT)', 1),
  (60, 'Plasmapheresis', 1),
  (60, 'Suturing of Laceration', 1),
  (60, 'Staple Removal', 1),
  (60, 'Drain Removal', 1),
  (60, 'Sebaceous Cyst Excision', 1),
  (60, 'Lipoma Excision', 1),
  (60, 'Corn Removal', 1),
  (60, 'Nail Avulsion (Ingrown Toe Nail)', 1),
  (60, 'Ganglion Excision', 1),
  (60, 'Mole Removal', 1),
  (60, 'Skin Biopsy (Punch/Excision)', 1),
  (60, 'Cautery for Warts', 1),
  (60, 'Cryotherapy', 1),
  (60, 'Chemical Peel', 1),
  (60, 'Laser Hair Removal', 1),
  (60, 'Tattoo Removal', 1),
  (60, 'Microdermabrasion', 1),
  (60, 'PRP Therapy (Platelet Rich Plasma)', 1),
  (60, 'Hair Transplant', 1),
  (60, 'Botox Injection', 1),
  (60, 'Dermal Fillers', 1),
  (60, 'Fine Needle Aspiration Cytology (FNAC)', 1),
  (60, 'True-Cut Biopsy', 1),
  (60, 'Excision Biopsy', 1),
  (60, 'Incision and Drainage (I&D)', 1),
  (60, 'Debridement of Wound', 1),
  (60, 'Burn Dressing', 1),
  (60, 'Skin Grafting', 1),
  (60, 'Flap Surgery', 1),
  (60, 'Bed Sore Dressing', 1),
  (60, 'VAC Dressing (Vacuum Assisted Closure)', 1),
  (60, 'Diabetic Foot Care', 1),
  (60, 'Amputation (Finger/Toe)', 1),
  (60, 'Amputation (Below Knee)', 1),
  (60, 'Amputation (Above Knee)', 1),
  (60, 'Plaster of Paris (POP) Application', 1),
  (60, 'Fiber Glass Cast Application', 1),
  (60, 'Slab Application', 1),
  (60, 'Cast Removal', 1),
  (60, 'Skin Traction Application', 1),
  (60, 'Skeletal Traction Application', 1),
  (60, 'Thomas Splint Application', 1),
  (60, 'Reduction of Dislocated Shoulder', 1),
  (60, 'Reduction of Dislocated Hip', 1),
  (60, 'Reduction of Fracture', 1),
  (60, 'K-Wire Fixation', 1),
  (60, 'External Fixator Application', 1),
  (60, 'Internal Fixation (Plating/Nailing)', 1),
  (60, 'Arthroscopy (Diagnostic)', 1),
  (60, 'ACL Reconstruction', 1),
  (60, 'Meniscus Repair', 1),
  (60, 'Total Knee Replacement (TKR)', 1),
  (60, 'Total Hip Replacement (THR)', 1),
  (60, 'Carpal Tunnel Release', 1),
  (60, 'Tendon Repair', 1),
  (60, 'Laminectomy', 1),
  (60, 'Discectomy', 1),
  (60, 'Spinal Fusion', 1),
  (60, 'Vertebroplasty', 1),
  (60, 'Kyphoplasty', 1),
  (60, 'ECG (Electrocardiogram)', 1),
  (60, 'Echocardiography (2D Echo)', 1),
  (60, 'Treadmill Test (TMT)', 1),
  (60, 'Holter Monitoring', 1),
  (60, 'Dobuatmine Stress Echo', 1),
  (60, 'Transesophageal Echocardiogram (TEE)', 1),
  (60, 'Coronary Angiography (CAG)', 1),
  (60, 'Angioplasty (PTCA) with Stenting', 1),
  (60, 'Balloon Valvuloplasty', 1),
  (60, 'Pacemaker Implantation (Temporary)', 1),
  (60, 'Pacemaker Implantation (Permanent)', 1),
  (60, 'CABG (Bypass Surgery)', 1),
  (60, 'Valve Replacement Surgery', 1),
  (60, 'Pericardiocentesis', 1),
  (60, 'Upper GI Endoscopy (OGD)', 1),
  (60, 'Colonoscopy', 1),
  (60, 'Sigmoidoscopy', 1),
  (60, 'ERCP', 1),
  (60, 'Polypectomy', 1),
  (60, 'Variceal Banding (EVL)', 1),
  (60, 'Sclerotherapy', 1),
  (60, 'Liver Biopsy', 1),
  (60, 'Paracentesis', 1),
  (60, 'Appendectomy (Open)', 1),
  (60, 'Appendectomy (Laparoscopic)', 1),
  (60, 'Cholecystectomy (Open)', 1),
  (60, 'Cholecystectomy (Laparoscopic)', 1),
  (60, 'Hernioplasty (Inguinal/Umbilical)', 1),
  (60, 'Exploratory Laparotomy', 1),
  (60, 'Hemorrhoidectomy (Piles Surgery)', 1),
  (60, 'Fistulotomy/Fistulectomy', 1),
  (60, 'Fissurectomy', 1),
  (60, 'Lateral Anal Sphincterotomy', 1),
  (60, 'Pilonidal Sinus Surgery', 1),
  (60, 'Whipple Procedure', 1),
  (60, 'Gastrectomy', 1),
  (60, 'Colectomy', 1),
  (60, 'Ileostomy Creation', 1),
  (60, 'Colostomy Creation', 1),
  (60, 'Stoma Closure', 1),
  (60, 'Circumcision', 1),
  (60, 'Hydrocele Surgery', 1),
  (60, 'Varicocele Surgery', 1),
  (60, 'Orchidectomy', 1),
  (60, 'Vasectomy', 1),
  (60, 'Cystoscopy', 1),
  (60, 'Urethral Dilatation', 1),
  (60, 'Suprapubic Cystostomy (SPC)', 1),
  (60, 'TURP (Prostate Surgery)', 1),
  (60, 'TURBT (Bladder Tumor)', 1),
  (60, 'Ureteroscopy (URS)', 1),
  (60, 'DJ Stent Insertion', 1),
  (60, 'DJ Stent Removal', 1),
  (60, 'PCNL (Kidney Stone Removal)', 1),
  (60, 'ESWL (Lithotripsy)', 1),
  (60, 'Nephrectomy', 1),
  (60, 'Pyelolithotomy', 1),
  (60, 'Urethroplasty', 1),
  (60, 'Normal Vaginal Delivery (NVD)', 1),
  (60, 'Assisted Breech Delivery', 1),
  (60, 'Forceps Delivery', 1),
  (60, 'Vacuum Assisted Delivery', 1),
  (60, 'LSCS (Caesarean Section)', 1),
  (60, 'Episiotomy Suturing', 1),
  (60, 'Dilatation and Curettage (D&C)', 1),
  (60, 'MTP (Medical Termination of Pregnancy)', 1),
  (60, 'Evacuation of Retained Products', 1),
  (60, 'Cervical Cerclage (McDonald''s Stitch)', 1),
  (60, 'Pap Smear Collection', 1),
  (60, 'Colposcopy', 1),
  (60, 'Hysteroscopy', 1),
  (60, 'Copper-T Insertion', 1),
  (60, 'Copper-T Removal', 1),
  (60, 'Tubectomy (Tubal Ligation)', 1),
  (60, 'Ovarian Cystectomy', 1),
  (60, 'Myomectomy', 1),
  (60, 'Hysterectomy (Abdominal)', 1),
  (60, 'Hysterectomy (Vaginal)', 1),
  (60, 'Laparoscopic Hysterectomy', 1),
  (60, 'Ectopic Pregnancy Surgery', 1),
  (60, 'IUI (Intrauterine Insemination)', 1),
  (60, 'IVF (In Vitro Fertilization)', 1),
  (60, 'Visual Acuity Test', 1),
  (60, 'Refraction (Glass Prescription)', 1),
  (60, 'Slit Lamp Examination', 1),
  (60, 'Tonometry (Eye Pressure)', 1),
  (60, 'Fundoscopy', 1),
  (60, 'Foreign Body Removal (Eye)', 1),
  (60, 'Syringing and Probing (Eye)', 1),
  (60, 'Subconjunctival Injection', 1),
  (60, 'Pterygium Excision', 1),
  (60, 'Chalazion Incision & Curettage', 1),
  (60, 'Cataract Surgery (SICS)', 1),
  (60, 'Cataract Surgery (Phacoemulsification)', 1),
  (60, 'Intravitreal Injection', 1),
  (60, 'Vitrectomy', 1),
  (60, 'DCR (Dacryocystorhinostomy)', 1),
  (60, 'Corneal Transplant', 1),
  (60, 'Lasik Surgery', 1),
  (60, 'Squint Correction', 1),
  (60, 'Otoscopy', 1),
  (60, 'Ear Wax Removal', 1),
  (60, 'Foreign Body Removal (Ear)', 1),
  (60, 'Foreign Body Removal (Nose)', 1),
  (60, 'Foreign Body Removal (Throat)', 1),
  (60, 'Pure Tone Audiometry (PTA)', 1),
  (60, 'Tympanometry', 1),
  (60, 'Nasal Endoscopy', 1),
  (60, 'Anterior Nasal Packing', 1),
  (60, 'Posterior Nasal Packing', 1),
  (60, 'Septoplasty', 1),
  (60, 'Tympanoplasty', 1),
  (60, 'Mastoidectomy', 1),
  (60, 'FESS (Sinus Surgery)', 1),
  (60, 'Tonsillectomy', 1),
  (60, 'Adenoidectomy', 1),
  (60, 'Laryngoscopy (Indirect/Direct)', 1),
  (60, 'Microlaryngoscopy', 1),
  (60, 'Thyroidectomy', 1),
  (60, 'Parotidectomy', 1),
  (60, 'Tooth Extraction', 1),
  (60, 'Surgical Tooth Extraction (Impaction)', 1),
  (60, 'Root Canal Treatment (RCT)', 1),
  (60, 'Dental Filling (Restoration)', 1),
  (60, 'Scaling and Polishing', 1),
  (60, 'Dental Crown Preparation', 1),
  (60, 'Bridge Fixation', 1),
  (60, 'Complete Denture Fabrication', 1),
  (60, 'Partial Denture Fabrication', 1),
  (60, 'Dental Implant Placement', 1),
  (60, 'Flap Surgery (Periodontal)', 1),
  (60, 'Orthodontic Bracing', 1),
  (60, 'Operculectomy', 1),
  (60, 'Alveoloplasty', 1),
  (60, 'Pulpectomy', 1),
  (60, 'Space Maintainer Application', 1),
  (60, 'EEG (Electroencephalogram)', 1),
  (60, 'EMG (Electromyography)', 1),
  (60, 'NCV (Nerve Conduction Velocity)', 1),
  (60, 'VEP (Visual Evoked Potential)', 1),
  (60, 'Sleep Study (Polysomnography)', 1),
  (60, 'Craniotomy', 1),
  (60, 'Burr Hole Evacuation', 1),
  (60, 'VP Shunt Insertion', 1),
  (60, 'Aneurysm Coiling/Clipping', 1),
  (60, 'Bronchoscopy', 1),
  (60, 'Thoracoscopy', 1),
  (60, 'Lung Biopsy', 1),
  (60, 'Lobectomy', 1),
  (60, 'Pneumonectomy', 1),
  (60, 'Pleurodesis', 1),
  (60, 'Pulmonary Function Test (PFT)', 1),
  (60, 'Mantoux Test', 1),
  (60, 'Allergy Skin Prick Test', 1),
  (60, 'Vaccination (Pediatric)', 1),
  (60, 'Vaccination (Adult)', 1),
  (60, 'Phototherapy (Newborn)', 1),
  (60, 'Exchange Transfusion', 1),
  (60, 'Umbilical Vein Catheterization', 1),
  (60, 'Surfactant Administration', 1),
  (60, 'Chemotherapy Administration', 1),
  (60, 'Radiotherapy Planning', 1),
  (60, 'Brachytherapy', 1),
  (60, 'Immunotherapy Infusion', 1),
  (60, 'Stem Cell Transplant', 1),
  (60, 'PET-CT Scan', 1),
  (60, 'MRI Scan (With/Without Contrast)', 1),
  (60, 'CT Scan (With/Without Contrast)', 1),
  (60, 'Mammography', 1),
  (60, 'DEXA Scan (Bone Density)', 1),
  (60, 'USG Guided Cyst Aspiration', 1),
  (60, 'CT Guided Biopsy', 1),
  (60, 'X-Ray Imaging', 1),
  (60, 'Barium Meal/Swallow', 1),
  (60, 'IVP (Intravenous Pyelogram)', 1),
  (60, 'Hysterosalpingography (HSG)', 1),
  (60, 'Doppler Study', 1),
  (60, 'Physiotherapy - Traction', 1),
  (60, 'Physiotherapy - TENS', 1),
  (60, 'Physiotherapy - IFT', 1),
  (60, 'Physiotherapy - Ultrasound', 1),
  (60, 'Physiotherapy - SWD', 1),
  (60, 'Physiotherapy - Wax Bath', 1),
  (60, 'Manual Therapy', 1),
  (60, 'Gait Training', 1),
  (60, 'Cardiac Rehabilitation', 1),
  (60, 'Neuro Rehabilitation', 1),
  (60, 'Speech Therapy', 1),
  (60, 'Occupational Therapy', 1),
  (60, 'Psychometric Assessment', 1),
  (60, 'ECT (Electroconvulsive Therapy)', 1),
  (60, 'Cognitive Behavioral Therapy (CBT)', 1),
  (60, 'De-addiction Therapy', 1),
  (60, 'Diet Counseling', 1),
  (60, 'Lactation Management', 1),
  (60, 'Sample Collection (Blood)', 1),
  (60, 'Sample Collection (Urine)', 1),
  (60, 'Sample Collection (Stool)', 1),
  (60, 'Sample Collection (Sputum)', 1),
  (60, 'Throat Swab Collection', 1),
  (60, 'Nasal Swab Collection', 1),
  (60, 'Wound Swab Collection', 1),
  (60, 'ABG (Arterial Blood Gas) Analysis', 1),
  (60, 'Glucometer Random Blood Sugar', 1),
  (60, 'Ketone Check', 1),
  (60, 'Rectal Examination', 1),
  (60, 'Proctoscopy', 1),
  (60, 'Vaginal Examination (PV)', 1),
  (60, 'Breast Examination', 1),
  (60, 'Testicular Examination', 1),
  (60, 'AV Fistula Creation', 1),
  (60, 'Permacath Insertion', 1),
  (60, 'Port-a-Cath Insertion', 1),
  (60, 'PICSE Line Insertion', 1),
  (60, 'Thrombolysis', 1),
  (60, 'Embolectomy', 1),
  (60, 'Varicose Vein Laser Surgery', 1),
  (60, 'Varicose Vein Stripping', 1),
  (60, 'Sclerotherapy for Veins', 1),
  (60, 'Lymph Node Biopsy', 1),
  (60, 'Sentinel Lymph Node Biopsy', 1),
  (60, 'Mastectomy (Radical/Simple)', 1),
  (60, 'Breast Conservation Surgery', 1),
  (60, 'Gynecomastia Surgery', 1),
  (60, 'Abdominoplasty (Tummy Tuck)', 1),
  (60, 'Liposuction', 1),
  (60, 'Rhinoplasty (Cosmetic)', 1),
  (60, 'Facelift', 1),
  (60, 'Blepharoplasty', 1),
  (60, 'Cleft Lip Repair', 1),
  (60, 'Cleft Palate Repair', 1),
  (60, 'Hypospadias Repair', 1),
  (60, 'Epispadias Repair', 1),
  (60, 'Undescended Testis Correction (Orchidopexy)', 1),
  (60, 'Tongue Tie Release', 1),
  (60, 'Pre-Anesthetic Checkup (PAC)', 1),
  (60, 'Epidural Injection', 1),
  (60, 'Spinal Anesthesia', 1),
  (60, 'General Anesthesia', 1),
  (60, 'Local Anesthesia Block', 1),
  (60, 'Nerve Block', 1),
  (60, 'Trigger Point Injection', 1),
  (60, 'Intra-articular Injection', 1),
  (60, 'Facet Joint Injection', 1),
  (60, 'Home Care Nursing', 1),
  (60, 'Palliative Care', 1),
  (60, 'Mortuary Care (Last Offices)', 1)
ON CONFLICT DO NOTHING;
